[package]
description = "xtask graphql-soup-schema: export the GraphQL Soup SDL to a file"
edition = "2024"
name = "xtask_graphql_soup_schema"
publish = false
version = "0.1.0"

[[bin]]
name = "xtask_graphql_soup_schema"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
xtask_paths = { path = "../xtask_paths" }
