module.exports = {
  propertiesService: {
    output: {
      client: 'zod',
      mode: 'split',
      target: './generated/zod.ts',
      schemas: './generated/schemas',
      indexFiles: false,
      biome: true,
      override: {
        header: ({ title, description, version }) => [
          'Generated by MacrOrval v7.1.1',
          '*DO NOT EDIT MANUALLY*',
          '',
          ...(title ? [title] : []),
          ...(description ? [description] : []),
          ...(version ? [`OpenAPI spec version: ${version}`] : []),
        ],
      },
    },
    input: {
      target: './openapi.json',
    },
  },
};
