// Usage:
// bun run scripts/generate-ai-tools-types.ts
//
// This script fetches AI tool schemas from the document-cognition service
// and generates TS types for use in the chat block and service package.

import { mkdir, readFile } from "node:fs/promises";
import * as path from "node:path";
import { join } from "node:path";
import { $ } from "bun";
import { resolveRefs } from "json-refs";
import { compile } from "json-schema-to-typescript";
import { jsonSchemaToZod } from "json-schema-to-zod";
import { z } from "zod";
import { documentCognitionBase, serviceUrl } from "./services";

/**
 * Pre-process JSON Schema to convert $ref with sibling properties into allOf.
 * json-refs doesn't properly merge $ref with sibling keywords (properties, required, etc.),
 * so we need to restructure the schema to use allOf for proper composition.
 */
function preprocessSchemaForRefs(schema: unknown): unknown {
	if (schema === null || typeof schema !== "object") {
		return schema;
	}

	if (Array.isArray(schema)) {
		return schema.map(preprocessSchemaForRefs);
	}

	const obj = schema as Record<string, unknown>;
	const result: Record<string, unknown> = {};

	// Check if this object has $ref along with other schema keywords
	if ("$ref" in obj) {
		const siblingKeys = Object.keys(obj).filter(
			(k) => k !== "$ref" && k !== "$schema" && k !== "description",
		);

		if (siblingKeys.length > 0) {
			// Convert to allOf structure: merge $ref schema with sibling properties
			const refPart = { $ref: obj.$ref };
			const siblingPart: Record<string, unknown> = {};

			for (const key of siblingKeys) {
				siblingPart[key] = preprocessSchemaForRefs(obj[key]);
			}

			// Keep description at top level if present
			if ("description" in obj) {
				result.description = obj.description;
			}

			result.allOf = [refPart, siblingPart];
			return result;
		}
	}

	// Recursively process all properties
	for (const [key, value] of Object.entries(obj)) {
		result[key] = preprocessSchemaForRefs(value);
	}

	return result;
}

const serviceDir = path.resolve(
	import.meta.dirname,
	documentCognitionBase.output,
);
const outputDir = join(serviceDir, "generated", "tools");
const schemasFile = join(outputDir, "schemas.ts");
const typesFile = join(outputDir, "types.ts");
const toolFile = join(outputDir, "tool.ts");

await $`rm ${schemasFile} ${toolFile} ${typesFile}|| true`;

const warning = `/* Generated by scripts/generate-ai-tools.ts
  * *DO NOT EDIT MANUALLY*
  *
*/`;

await mkdir(outputDir, { recursive: true });

const AiToolsResponseSchema = z.object({
	schemas: z.array(
		z.object({
			name: z.string(),
			inputSchema: z.any(),
			outputSchema: z.any(),
		}),
	),
});

type AiToolsResponse = z.infer<typeof AiToolsResponseSchema>["schemas"];

async function fetchAIToolsSchemas(): Promise<AiToolsResponse> {
	const path =
		"../../rust/cloud-storage/document_cognition_service/schemas/tools.json";
	try {
		const data = await readFile(path, "utf-8");
		const parsed = AiToolsResponseSchema.parse(JSON.parse(data));
		console.log(`Successfully loaded ${parsed.schemas.length} AI tool schemas`);
		return parsed.schemas;
	} catch (error) {
		console.error("Failed to load AI tools schemas:", error);
		throw error;
	}
}

async function generateSchemasFile(tools: AiToolsResponse) {
	// Generate all schemas, deduplicating by title
	const generatedSchemas = new Set<string>();
	const content: Array<string> = [];

	for (const tool of tools) {
		// jsonSchemaToZod with name option generates a proper export
		// Preprocess to handle $ref with sibling properties
		const preprocessedInput = preprocessSchemaForRefs(tool.inputSchema);
		const { resolved: inputSchema } = await resolveRefs(preprocessedInput);
		if (!generatedSchemas.has(inputSchema.title)) {
			const inputCode = jsonSchemaToZod(inputSchema, {
				module: "esm",
				name: inputSchema.title,
				withoutDescribes: true,
				noImport: true,
			});
			content.push(inputCode);
			generatedSchemas.add(inputSchema.title);
		}

		const preprocessedOutput = preprocessSchemaForRefs(tool.outputSchema);
		const { resolved: outputSchema } = await resolveRefs(preprocessedOutput);
		if (!generatedSchemas.has(outputSchema.title)) {
			const outputCode = jsonSchemaToZod(outputSchema, {
				module: "esm",
				name: outputSchema.title,
				withoutDescribes: true,
				noImport: true,
			});
			content.push(outputCode);
			generatedSchemas.add(outputSchema.title);
		}
	}

	const contents = `${warning}
import { z } from 'zod';

${content.join("\n\n")}
`;

	await Bun.write(schemasFile, contents);
}

/**
 * Remove duplicate type/interface declarations from generated TypeScript code.
 * json-schema-to-typescript generates nested types inline, which can cause duplicates
 * when multiple schemas reference the same type.
 */
function deduplicateTypes(code: string): string {
	const seenTypes = new Set<string>();
	const lines = code.split("\n");
	const result: string[] = [];
	let skipUntilNextExport = false;
	let braceCount = 0;

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];

		// Check if we're starting a new export type or interface
		const typeMatch = line.match(
			/^export\s+(type|interface)\s+(\w+)(?:\s*=|\s*\{|\s*$)/,
		);

		if (typeMatch && !skipUntilNextExport) {
			const typeName = typeMatch[2];

			if (seenTypes.has(typeName)) {
				// Skip this duplicate type definition
				skipUntilNextExport = true;
				braceCount = 0;
				// Count opening braces on this line
				braceCount += (line.match(/\{/g) || []).length;
				braceCount -= (line.match(/\}/g) || []).length;
				// If it's a type alias (ends with ;), skip just this line
				if (line.includes(";") && braceCount === 0) {
					skipUntilNextExport = false;
				}
				continue;
			}
			seenTypes.add(typeName);
		}

		if (skipUntilNextExport) {
			// Count braces to know when the type/interface ends
			braceCount += (line.match(/\{/g) || []).length;
			braceCount -= (line.match(/\}/g) || []).length;

			// For type aliases, check if line ends with semicolon at brace level 0
			if (braceCount <= 0 && (line.includes(";") || line.trim() === "}")) {
				skipUntilNextExport = false;
			}
			continue;
		}

		result.push(line);
	}

	return result.join("\n");
}

async function generateToolTypesFile(tools: AiToolsResponse) {
	// Generate all schemas, deduplicating by title
	const generatedTypes = new Set<string>();
	const content: Array<string> = [];

	for (const tool of tools) {
		// Preprocess to handle $ref with sibling properties
		const preprocessedInput = preprocessSchemaForRefs(tool.inputSchema);
		if (!generatedTypes.has(tool.inputSchema.title)) {
			const inputCode = await compile(
				preprocessedInput,
				tool.inputSchema.title,
				{
					// override top level name for export
					customName: (schema) => {
						if (schema.title) {
							console.log(`Using schema title: ${schema.title}`);
							return schema.title;
						}
					},
					additionalProperties: false,
					style: {
						singleQuote: true,
					},
				},
			);
			content.push(inputCode);
			generatedTypes.add(tool.inputSchema.title);
		}

		const preprocessedOutput = preprocessSchemaForRefs(tool.outputSchema);
		if (!generatedTypes.has(tool.outputSchema.title)) {
			const outputCode = await compile(
				preprocessedOutput,
				tool.outputSchema.title,
				{
					// override top level name for export
					customName: (schema) => {
						if (schema.title) {
							console.log(`Using schema title: ${schema.title}`);
							return schema.title;
						}
						return undefined;
					},
					additionalProperties: false,
					style: {
						singleQuote: true,
					},
				},
			);
			content.push(outputCode);
			generatedTypes.add(tool.outputSchema.title);
		}
	}

	// Deduplicate nested types that may have been generated multiple times
	const rawContents = `${warning}
${content.join("\n\n")}
`;
	const deduplicatedContents = deduplicateTypes(rawContents);

	await Bun.write(typesFile, deduplicatedContents);
}

async function generateToolsFile(tools: AiToolsResponse) {
	// Resolve schemas to get titles
	const toolsWithTitles = await Promise.all(
		tools.map(async (tool) => {
			const preprocessedInput = preprocessSchemaForRefs(tool.inputSchema);
			const preprocessedOutput = preprocessSchemaForRefs(tool.outputSchema);
			const { resolved: inputSchema } = await resolveRefs(preprocessedInput);
			const { resolved: outputSchema } = await resolveRefs(preprocessedOutput);
			return {
				name: tool.name,
				inputTitle: inputSchema.title,
				outputTitle: outputSchema.title,
			};
		}),
	);

	const contents = `${warning}

import { err, type MaybeResult, ok } from 'core/util/maybeResult';
import type { Component } from 'solid-js';
import * as schemas from './schemas';
import type * as types from './types';

type ToolParserMap = {
${toolsWithTitles
	.map(
		(tool) =>
			`${tool.name}: { call: types.${tool.inputTitle}, response: types.${tool.outputTitle} }`,
	)
	.join("\n")}
};

const toolParserMap = {
${toolsWithTitles
	.map(
		(tool) =>
			`${tool.name}: { call: schemas.${tool.inputTitle}, response: schemas.${tool.outputTitle} }`,
	)
	.join(",\n")}
};

export type ToolName = keyof ToolParserMap;

type NamedRawTool = {
  id: string;
  name: string;
  json: unknown;
};

type ToolDataMap = {
${toolsWithTitles
	.map(
		(tool) =>
			`${tool.name}: { call: types.${tool.inputTitle}, response: types.${tool.outputTitle} }`,
	)
	.join(";\n")};
};

export type NamedTool<
  TName extends ToolName = ToolName,
  TDirection extends 'call' | 'response' = 'call' | 'response',
> = {
  id: string;
  name: TName;
  data: ToolDataMap[TName][TDirection];
};

export type ToolContext<TTool extends NamedTool = NamedTool> = {
  tool: TTool;
  chat_id: string;
  message_id: string;
  part_index: number;
  isComplete: boolean;
};

export interface ToolHandler<T extends NamedTool, RenderContext> {
  handle?: (context: ToolContext<T>) => void | Promise<void>;
  render?: Component<ToolContext<T> & RenderContext>;
}

function deserializeTool<T extends NamedTool>(
  tool: NamedRawTool,
  direction: 'call' | 'response'
): MaybeResult<'parse_error' | 'not_found', T> {
  if (!(tool.name in toolParserMap)) {
    return err('not_found', \`tool name not found \${tool.name}\`);
  }
  const parser = toolParserMap[tool.name as ToolName];
  const maybeToolCall = parser[direction].safeParse(tool.json);
  if (maybeToolCall.success) {
    return ok({
      id: tool.id,
      name: tool.name as ToolName,
      data: maybeToolCall.data,
    } as T);
  }
  return err('parse_error', 'tool parsing failed');
}

export function deserializeToolCall(
  tool: NamedRawTool
): MaybeResult<'parse_error' | 'not_found', NamedTool<ToolName, 'call'>> {
  return deserializeTool(tool, 'call');
}

export function deserializeToolResponse(
  tool: NamedRawTool
): MaybeResult<'parse_error' | 'not_found', NamedTool<ToolName, 'response'>> {
  return deserializeTool(tool, 'response');
}

export type ToolHandlerMap<RenderContext>= {
  [K in ToolName]: {
    call: ToolHandler<NamedTool<K, 'call'>,RenderContext>;
    response: ToolHandler<NamedTool<K, 'response'>, RenderContext>;
  };
};
`;
	await Bun.write(toolFile, contents);
}

// Fetch AI tools schemas
const tools = await fetchAIToolsSchemas();
// Sort tools by name to maintain consistent order
tools.sort((a, b) => a.name.localeCompare(b.name));
// write types
await generateSchemasFile(tools);
await generateToolsFile(tools);
await generateToolTypesFile(tools);
await $`bunx biome format --write --no-errors-on-unmatched ${toolFile} ${schemasFile} ${typesFile}`;

console.log(
	`Generated AI tools types at: ${serviceDir}/generated/tools/tools.ts`,
);

console.log("✅ AI tools types generation completed successfully");
