#!/usr/bin/env bun
import * as path from 'node:path';
import { join } from 'path';
import { documentCognitionBase, serviceUrl } from "./services"
import { z } from "zod";

const outputDir = path.resolve(import.meta.dirname, documentCognitionBase.output);
const outputFile = join(outputDir, "generated", "schemas", "model.ts")

const ModelSchema = z.object({
    name: z.string(),
    provider: z.string(),
    metadata: z.object({
      contextWindow: z.number(),
    })
});

const ModelResponseSchema = z.object({
  models: z.array(ModelSchema)
})

type ModelResponse = z.infer<typeof ModelResponseSchema>;

async function fetchModels(): Promise<ModelResponse> {

  const baseUrl = serviceUrl(documentCognitionBase)

    const response = await fetch(`${baseUrl}/models`);
    if (!response.ok){
      throw new Error("bad response from DCS")
    }
    const models = await response.json();

    return ModelResponseSchema.parse(models);
}

function modelType(models: ModelResponse): string {
  return `export type Model = typeof Model[keyof typeof Model];

export const Model = {
${models.models
  .map(model => (
    `  "${model.name}": "${model.name}",`
  ))
  .join("\n")
}
} as const;`
}


function warning(): string {
  return`/* Generated by scripts/generate-models-enum.ts
  * *DO NOT EDIT MANUALLY*
  *
  * Model names enum generated from document-cognition/models endpoint
*/`
}

function allModels(models: ModelResponse): string {
  return `
export const AllModels: Model[] = [
${models.models.map(model => (`  "${model.name}"`)).join(',\n')}
] as const;
const values: [Model, ...Model[]] = [
Object.values(Model)[0],
...Object.values(Model).slice(1),
];

export const ModelEnum = z.enum(values);


`

}


const models = await fetchModels();
const contents = [
  warning(),
  "import {z} from 'zod';",
  modelType(models),
  allModels(models)
].join("\n");

await Bun.write(outputFile, contents)
