// Usage:
// bun run scripts/generate-dcs-tools.ts
//
// This script generates AI tool schemas by running the local Rust binary
// and generates TS types for use in the chat block and service package.

import { mkdir, readFile } from 'node:fs/promises';
import * as path from 'node:path';
import { $ } from 'bun';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import { compile } from 'json-schema-to-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { z } from 'zod';
import { documentCognitionBase } from './services';

const rustCloudStorageDir = path.resolve(
  import.meta.dirname,
  '../../../rust/cloud-storage'
);
const aiToolsDir = path.join(rustCloudStorageDir, 'ai_tools');
const schemasJsonPath = path.join(aiToolsDir, 'schemas', 'tools.json');

const serviceDir = path.resolve(
  import.meta.dirname,
  documentCognitionBase.output
);
const outputDir = path.join(serviceDir, 'generated', 'tools');
const schemasFile = path.join(outputDir, 'schemas.ts');
const typesFile = path.join(outputDir, 'types.ts');
const toolFile = path.join(outputDir, 'tool.ts');

await $`rm ${schemasFile} ${toolFile} ${typesFile}|| true`;

const warning = `/* Generated by scripts/generate-dcs-tools.ts
 * *DO NOT EDIT MANUALLY*
 */`;

await mkdir(outputDir, { recursive: true });

// The combined schema has shared $defs and a tools array
const CombinedSchemaValidator = z.object({
  $defs: z.record(z.any()),
  tools: z.array(
    z.object({
      name: z.string(),
      input: z.string(),
      output: z.string(),
    })
  ),
});

type CombinedSchema = z.infer<typeof CombinedSchemaValidator>;

async function buildAndRunSchemaGenerator(): Promise<void> {
  console.log('Building gen_tool_schemas binary...');
  await $`cd ${rustCloudStorageDir} && SQLX_OFFLINE=true cargo build --bin gen_tool_schemas`;
  console.log('Build complete.');

  await $`rm -rf ${path.join(aiToolsDir, 'schemas')}`.quiet();

  console.log('Running gen_tool_schemas...');
  const binaryPath = path.join(
    rustCloudStorageDir,
    'target',
    'debug',
    'gen_tool_schemas'
  );
  await $`cd ${aiToolsDir} && ${binaryPath}`;
  console.log('Schema generation complete.');
}

async function loadCombinedSchema(): Promise<CombinedSchema> {
  await buildAndRunSchemaGenerator();
  const data = await readFile(schemasJsonPath, 'utf-8');
  const parsed = CombinedSchemaValidator.parse(JSON.parse(data));
  console.log(
    `Loaded ${parsed.tools.length} tools, ${Object.keys(parsed.$defs).length} definitions`
  );
  return parsed;
}

async function generateSchemasFile(schema: CombinedSchema) {
  const resolved = await $RefParser.dereference(structuredClone(schema));
  const defs = (resolved as Record<string, unknown>).$defs as Record<
    string,
    unknown
  >;
  const seen = new Set<string>();
  const content: string[] = [];

  for (const tool of schema.tools) {
    for (const defName of [tool.input, tool.output]) {
      if (seen.has(defName)) continue;
      seen.add(defName);

      const resolvedDef = defs[defName];
      const schemaWithTitle = { ...resolvedDef, title: defName };

      content.push(
        jsonSchemaToZod(schemaWithTitle, {
          module: 'esm',
          name: defName,
          withoutDescribes: true,
          noImport: true,
        })
      );
    }
  }

  await Bun.write(
    schemasFile,
    `${warning}\nimport { z } from 'zod/v3';\n\n${content.join('\n\n')}\n`
  );
}

async function generateToolTypesFile(schema: CombinedSchema) {
  const properties: Record<string, unknown> = {};
  for (const key of Object.keys(schema.$defs)) {
    properties[key] = { $ref: `#/$defs/${key}` };
  }

  const code = await compile(
    {
      $defs: schema.$defs,
      type: 'object',
      properties,
      additionalProperties: false,
    },
    'AllToolTypes',
    {
      additionalProperties: false,
      style: { singleQuote: true },
    }
  );

  // Strip the root wrapper interface — we only want the definition types
  const cleaned = code.replace(
    /export interface AllToolTypes\s*\{[\s\S]*?\n\}\n*/,
    ''
  );

  await Bun.write(typesFile, `${warning}\n${cleaned}`);
}

async function generateToolsFile(schema: CombinedSchema) {
  const entries = schema.tools
    .map((t) => ({
      name: t.name,
      inputTitle: t.input,
      outputTitle: t.output,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  const contents = `${warning}

import { err, type MaybeResult, ok } from 'core/util/maybeResult';
import * as schemas from './schemas';
import type * as types from './types';

type ToolParserMap = {
${entries
  .map(
    (t) =>
      `${t.name}: { call: types.${t.inputTitle}, response: types.${t.outputTitle} }`
  )
  .join('\n')}
};

const toolParserMap = {
${entries
  .map(
    (t) =>
      `${t.name}: { call: schemas.${t.inputTitle}, response: schemas.${t.outputTitle} }`
  )
  .join(',\n')}
};

export type ToolName = keyof ToolParserMap;

type NamedRawTool = {
  id: string;
  name: string;
  json: unknown;
};

type ToolDataMap = {
${entries
  .map(
    (t) =>
      `${t.name}: { call: types.${t.inputTitle}, response: types.${t.outputTitle} }`
  )
  .join(';\n')};
};

export type NamedTool<
  TName extends ToolName = ToolName,
  TDirection extends 'call' | 'response' = 'call' | 'response',
> = {
  id: string;
  name: TName;
  data: ToolDataMap[TName][TDirection];
};

function deserializeTool<T extends NamedTool>(
  tool: NamedRawTool,
  direction: 'call' | 'response'
): MaybeResult<'parse_error' | 'not_found', T> {
  if (!(tool.name in toolParserMap)) {
    return err('not_found', \`tool name not found \${tool.name}\`);
  }
  const parser = toolParserMap[tool.name as ToolName];
  const maybeToolCall = parser[direction].safeParse(tool.json);
  if (maybeToolCall.success) {
    return ok({
      id: tool.id,
      name: tool.name as ToolName,
      data: maybeToolCall.data,
    } as T);
  }
  return err('parse_error', 'tool parsing failed');
}

export function deserializeToolCall(
  tool: NamedRawTool
): MaybeResult<'parse_error' | 'not_found', NamedTool<ToolName, 'call'>> {
  return deserializeTool(tool, 'call');
}

export function deserializeToolResponse(
  tool: NamedRawTool
): MaybeResult<'parse_error' | 'not_found', NamedTool<ToolName, 'response'>> {
  return deserializeTool(tool, 'response');
}
`;
  await Bun.write(toolFile, contents);
}

const schema = await loadCombinedSchema();

await generateSchemasFile(schema);
await generateToolsFile(schema);
await generateToolTypesFile(schema);

// On NixOS, the npm-installed biome binary doesn't work due to dynamic linking issues.
const isNixOS =
  process.env.NIX_PATH !== undefined ||
  ((await Bun.file('/etc/os-release').exists()) &&
    (await Bun.file('/etc/os-release').text()).includes('NixOS'));
if (isNixOS) {
  const systemBiomePath =
    await $`bash -c 'PATH=$(echo "$PATH" | tr ":" "\n" | grep -v node_modules | tr "\n" ":") which biome'`.text();
  await $`${systemBiomePath.trim()} format --write --no-errors-on-unmatched ${toolFile} ${schemasFile} ${typesFile}`;
} else {
  await $`biome format --write --no-errors-on-unmatched ${toolFile} ${schemasFile} ${typesFile}`;
}

console.log(`Generated AI tools types at: ${outputDir}`);
console.log('✅ AI tools types generation completed successfully');
