config:
  aws:region: us-east-1
  github-runners:instanceType: t3.large
  github-runners:runnerUrl: https://github.com/macro-inc
  github-runners:runnerToken:
    secure: AAABAITqpBY+NbTOaeJMHl8tYniMcggbPuYplw4WAc6giqK4HPdLE/OkMCKLuCqCcs62bEj85Muq1401GQ==
