[package]
edition = "2024"
name = "document_storage_service_client"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
model = { path = "../model" }
model_owner = { path = "../model_owner" }
models_bulk_upload = { path = "../models_bulk_upload" }
models_permissions = { path = "../models_permissions" }
reqwest = { workspace = true, features = ["query"] }
rootcause = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared_entity_registry = { path = "../entity_registry/shared_entity_registry" }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
bot_id = { path = "../bot_id" }
tokio = { workspace = true }
wiremock = { workspace = true }
