/** Regenerate the offline SDK embedded in the Deno runner and its MCP help. */
import { fileURLToPath } from 'node:url';
import { sdkDocs } from '../src/code-mode/sdk-docs';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const result = await Bun.build({
  entrypoints: [`${root}services/ai-editing-worker/src/code-mode/sdk.ts`],
  target: 'browser',
  format: 'esm',
  minify: true,
  loader: { '.md': 'text' },
});
if (!result.success) throw new AggregateError(result.logs, 'SDK build failed');
const output = `// Generated by services/ai-editing-worker/scripts/generate-code-sdk.ts.\n${await result.outputs[0]!.text()}`;
for (const [path, contents] of [
  ['crates/code_execution/src/outbound/deno/sdk.mjs', output],
  [
    'crates/agent_code_mode/src/sdk-docs.json',
    `${JSON.stringify(sdkDocs, null, 2)}\n`,
  ],
]) {
  const file = `${root}${path}`;
  if (Bun.argv.includes('--check')) {
    if ((await Bun.file(file).text()) !== contents)
      throw new Error(
        `${path} is stale; run bun services/ai-editing-worker/scripts/generate-code-sdk.ts`
      );
  } else await Bun.write(file, contents!);
}
