/**
 * Transpiles DocumentEditor + EditError to plain JS and writes editor-sandbox-code.ts.
 * Run via `bun scripts/generate-sandbox.ts` (wired into prebuild).
 */
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const t = new Bun.Transpiler({ loader: 'ts' });

async function transpile(relPath: string): Promise<string> {
  const src = await Bun.file(join(root, relPath)).text();
  // Strip import/export — QuickJS evaluates a plain script, not an ES module.
  return t.transformSync(src)
    .replace(/^import\s.*$/gm, '')
    .replace(/^export\s+(?:default\s+)?/gm, '')
    .trim();
}

const code = [
  await transpile('src/ai-editing/editor/errors.ts'),
  await transpile('src/ai-editing/editor/document-editor.ts'),
].join('\n\n');

const out = `// Auto-generated by scripts/generate-sandbox.ts — do not edit.
// Source of truth: src/ai-editing/editor/document-editor.ts
export const SANDBOX_CODE = ${JSON.stringify(code)};
`;

await Bun.write(join(root, 'src/editor-sandbox-code.ts'), out);
console.log('generated src/editor-sandbox-code.ts');
