[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "ctx7sk-b7404c8c-945c-451a-9233-7c1d74da944d"

[mcp_servers.datadog-mcp]
url = "https://mcp.us5.datadoghq.com/api/unstable/mcp-server/mcp"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.playwright]
args = [
    "@playwright/mcp@latest",
    "--config=/Users/synoet/dev/macro/macro/js/app/e2e-specs/playwright-config.json",
]
command = "npx"
