// Re-export domain types from the existing @core/component/Properties package.
// Source of truth lives there for now; a future PR will flip ownership to @property.

export type {
  ApiError,
  BooleanProperty,
  DataType,
  DateProperty,
  EntityPropertiesResponse,
  EntityProperty,
  EntityPropertyWithDefinition,
  EntityReference,
  LinkProperty,
  MultiValueProperty,
  NumberProperty,
  PropertiesPanelProps,
  Property,
  PropertyApiValues,
  PropertyDefinitionDomain,
  PropertyDefinitionResponse,
  PropertyEditorProps,
  PropertyOption,
  PropertyOptionValue,
  PropertySelectorProps,
  PropertyValue,
  Result,
  SelectNumberProperty,
  SelectProperty,
  SelectStringProperty,
  SetPropertyValue,
  SingleValueProperty,
  StringProperty,
  ValueType,
} from '@core/component/Properties/types';
