//! Opt-in per-instance overlay pointing calendar watch channels at the dev
//! relay, so real Google Calendar push reaches a local stack.
//!
//! `enable` mints a per-instance channel token and writes `calendar-push.env`
//! into the instance's artifact dir; `env_layer::resolve` overlays that file
//! on every subsequent resolve (up, update, validate, snapshot), which keeps
//! every verb consistent without threading a flag through each of them. The
//! relay shared secret is intentionally NOT written here — it is a real
//! secret and must arrive through Doppler or `--env-file` as
//! `CALENDAR_WATCH_RELAY_SECRET`.

use std::io::Read;
use std::path::PathBuf;

use anyhow::{Context, Result, bail};

use super::instance::Instance;

/// The dev-only tunnel service that receives Google's webhooks on the local
/// stack's behalf and relays them out (its hostname is a subdomain of
/// macro.com, already verified in the Cloud project owning the OAuth client,
/// which a laptop's never can be).
const DEV_TUNNEL: &str = "https://calendar-event-local-tunnel-dev.macro.com";

/// The overlay consumed by `env_layer::resolve` when present.
pub fn env_path(instance: &Instance) -> PathBuf {
    instance.artifact_dir().join("calendar-push.env")
}

fn token_path(instance: &Instance) -> PathBuf {
    instance.artifact_dir().join("calendar-push.token")
}

/// Mint the instance's channel token once and reuse it across enables, so
/// re-enabling never orphans channels opened under a previous token. Only a
/// genuinely absent file mints: any other read failure (or a corrupt empty
/// file) must not silently rotate the token out from under open channels.
fn ensure_token(instance: &Instance) -> Result<String> {
    let path = token_path(instance);
    match std::fs::read_to_string(&path) {
        Ok(existing) => {
            let existing = existing.trim();
            if existing.is_empty() {
                bail!(
                    "calendar push token file {} is empty — delete it to mint a fresh token",
                    path.display()
                );
            }
            return Ok(existing.to_owned());
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(error).with_context(|| format!("reading {}", path.display()));
        }
    }
    let mut bytes = [0u8; 32];
    std::fs::File::open("/dev/urandom")
        .and_then(|mut file| file.read_exact(&mut bytes))
        .context("reading /dev/urandom for the calendar push token")?;
    let token: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    instance.ensure_artifact_dir()?;
    std::fs::write(&path, &token).with_context(|| format!("writing {}", path.display()))?;
    Ok(token)
}

/// Write the overlay so the next resolve arms calendar push.
pub fn enable(instance: &Instance) -> Result<()> {
    let token = ensure_token(instance)?;
    let path = env_path(instance);
    let contents = format!(
        "# GENERATED by `just calendar-push enable` — remove via `just calendar-push disable`.\n\
         CALENDAR_WATCH_WEBHOOK_URL={DEV_TUNNEL}/calendar/notifications\n\
         CALENDAR_WATCH_RELAY_URL={DEV_TUNNEL}\n\
         CALENDAR_WATCH_TOKEN={token}\n"
    );
    std::fs::write(&path, contents).with_context(|| format!("writing {}", path.display()))?;
    println!(
        "calendar push ENABLED for instance {} — takes effect on the next `just run_local` (or `just stack update`)",
        instance.name()
    );
    println!("  overlay  {}", path.display());
    println!(
        "  requires CALENDAR_WATCH_RELAY_SECRET (Doppler or --env-file) and calendar sync enabled"
    );
    Ok(())
}

/// Remove the overlay. The instance token is kept so a later enable reuses
/// it; a currently running stack keeps its channels until it shuts down
/// (graceful shutdown stops them at Google).
pub fn disable(instance: &Instance) -> Result<()> {
    let path = env_path(instance);
    if path.is_file() {
        std::fs::remove_file(&path).with_context(|| format!("removing {}", path.display()))?;
        println!(
            "calendar push DISABLED for instance {} — takes effect on the next `just run_local` (or `just stack update`)",
            instance.name()
        );
    } else {
        println!(
            "calendar push already disabled for instance {}",
            instance.name()
        );
    }
    Ok(())
}

/// Report whether the overlay is present.
pub fn status(instance: &Instance) -> Result<()> {
    let path = env_path(instance);
    if path.is_file() {
        println!("calendar push: ENABLED ({})", path.display());
    } else {
        println!("calendar push: disabled");
    }
    Ok(())
}
