DATABASE_URL := "postgres://user:password@localhost:5432/macrodb"

mod sqlx '../sqlx.just'

prepare_db:
    just sqlx::prepare_db {{ DATABASE_URL }}

build:
  cargo build

check:
  cargo clippy

run:
    #!/usr/bin/env bash
    set -a
    source .env
    set +a
    cargo run --bin service --features local_auth
