#[cfg(test)]
mod tests;

/// Checks if an email address is likely a generic/automated system email
///
/// This function identifies common patterns in email addresses that typically
/// indicate automated senders rather than individual users.
pub fn is_generic_email(email: &str) -> bool {
    let email_lower = email.to_lowercase();

    // if it's really long, it's probably an autogenerated email address
    if email.len() > 50 {
        return true;
    }

    // Common automated email prefixes
    let automated_prefixes = [
        "reply",
        "noreply",
        "no-reply",
        "do-not-reply",
        "donotreply",
        "auto",
        "automated",
        "alert",
        "alerts",
        "notification",
        "notifications",
        "info",
        "information",
        "news",
        "newsletter",
        "updates",
        "support",
        "help",
        "helpdesk",
        "service",
        "services",
        "system",
        "admin",
        "administrator",
        "account",
        "accounts",
        "billing",
        "contact",
        "team",
        "no_reply",
        "do_not_reply",
        "mailer",
        "mail",
        "postmaster",
        "robot",
        "confirm",
        "confirmation",
        "verify",
        "verification",
        "security",
        "secure",
        "webmaster",
        "customercare",
        "customer-care",
        "customer.care",
        "customerservice",
        "customer-service",
        "customer.service",
        "feedback",
        "hello",
        "hi",
        "welcome",
        "marketing",
        "careers",
        "jobs",
        "applications",
        "receipts",
        "receipt",
        "order",
        "orders",
        "shipping",
        "delivery",
        "track",
        "tracking",
        "sales",
        "dev",
        "developer",
        "api",
        "test",
        "testing",
        "noreply-",
        "no-reply-",
        "no.reply.",
        "donotreply-",
        "do-not-reply-",
        "do.not.reply.",
    ];

    // Check if email starts with any of the automated prefixes
    // We check specifically for prefix@ pattern to avoid matching personal emails
    // that might contain these words elsewhere
    for prefix in automated_prefixes {
        if email_lower.starts_with(prefix)
            && (email_lower.contains(&format!("{}@", prefix))
                || email_lower.contains(&format!("{}-", prefix))
                || email_lower.contains(&format!("{}.", prefix))
                || email_lower.contains(&format!("{}+", prefix))
                || email_lower.contains(&format!("{}=", prefix))
                || email_lower.contains(&format!("{}_", prefix)))
        {
            return true;
        }
    }

    // Check for common patterns for system accounts
    if email_lower.contains("@")
        && (email_lower.contains("noreply")
            || email_lower.contains("no-reply")
            || email_lower.contains("no.reply")
            || email_lower.contains("no_reply")
            || email_lower.contains("do-not-reply")
            || email_lower.contains("donotreply")
            || email_lower.contains("system")
            || email_lower.contains("notification")
            || email_lower.contains("automated")
            || email_lower.contains("unsub")
            || email_lower.contains("support")
            || email_lower.contains("do_not_reply"))
    {
        return true;
    }

    // Check for specific domains or addresses that typically send automated emails
    let system_domains = [
        "@sendgrid.net",
        "@mailchimp.com",
        "@sendgrid.com",
        "@amazonses.com",
        "@email.amazonses.com",
        "@bounce.amazonses.com",
        "@sparkpost.com",
        "@mailgun.org",
        "@mg.mailgun.org",
        "@postman.com",
        "@salesforce.com",
        "@salesforceiq.com",
        "@hubspot.com",
        "@marketo.com",
        "@mailjet.com",
        "@sendgrid.net",
        "@constant.com",
        "@constantcontact.com",
    ];

    for domain in system_domains {
        if email_lower.ends_with(domain) {
            return true;
        }
    }

    // Check common automated email patterns where @ is preceded by numbers or codes
    if let Some(at_pos) = email_lower.find('@') {
        let local_part = &email_lower[0..at_pos];

        // Check if local part consists only of numbers or contains certain patterns
        if local_part
            .chars()
            .all(|c| c.is_numeric() || c == '.' || c == '-' || c == '_')
            && local_part.chars().any(|c| c.is_numeric())
        {
            return true;
        }

        // Check for common notification-type IDs
        if local_part.starts_with("id") && local_part.chars().skip(2).all(|c| c.is_numeric()) {
            return true;
        }
    }

    false
}
