lambda_name := file_name(justfile_directory())

test:
    cargo test --all-features

build compiler="":
	cargo lambda build {{ if compiler == "" { "" } else { "--compiler " + compiler } }} --release --bin {{lambda_name}} --output-format zip

watch:
    cargo lambda watch -F local

# invoke the lambda locally after watch is running
invoke:
    cargo lambda invoke {{lambda_name}} --data-file event.json 
