[package]
edition = "2024"
name = "channel_sender"
publish = false
version = "0.1.0"

[dependencies]
bot_id = { path = "../bot_id" }
either = { workspace = true }
macro_user_id = { path = "../macro_user_id" }
serde = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
serde_json = { workspace = true }
uuid = { workspace = true }
