DATABASE_URL := "postgres://user:password@localhost:5432/macrodb"

export AWS_ACCESS_KEY_ID := env('AWS_ACCESS_KEY_ID', 'dummy')
export AWS_SECRET_ACCESS_KEY := env('AWS_SECRET_ACCESS_KEY', 'dummy')

mod ensure '../ensure.just'
mod sqlx '../sqlx.just'

prepare_db:
    just sqlx::prepare_db {{ DATABASE_URL }}

integration_test *FLAGS: ensure::ensure_dynamodb
    ENVIRONMENT=local cargo test --all-features {{ FLAGS }}
