{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    fenix.url = "github:nix-community/fenix";
    fenix.inputs.nixpkgs.follows = "nixpkgs";
    crane.url = "github:ipetkov/crane";
    rs-libreoffice-bindings.url = "github:macro-inc/rs-libreoffice-bindings/dev";
    rs-libreoffice-bindings.flake = false;
  };
  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      fenix,
      crane,
      rs-libreoffice-bindings,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          system = system;
        };
        isDarwin = pkgs.stdenv.isDarwin;
        isLinux = pkgs.stdenv.isLinux;

        # ── cloud-storage (Rust backend) ──────────────────────────────

        rustToolchain = fenix.packages.${system}.fromToolchainFile {
          file = ./rust/rust-toolchain.toml;
          sha256 = "sha256-qqF33vNuAdU5vua96VKVIwuc43j4EFeEXbjQ6+l4mO4=";
        };

        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;

        libraries =
          with pkgs;
          [
            openssl
            openssl.dev
            glib
            glib.dev
            libclang
          ]
          ++ pkgs.lib.optionals isLinux [
            glibc.dev
            gcc
          ]
          ++ pkgs.lib.optionals isDarwin [
            libiconv
          ];

        # Include Cargo sources plus the .sqlx offline query cache.
        # rs-libreoffice-bindings lives outside the repo; we import it explicitly
        # so the nix sandbox can resolve the path dep in convert_service.
        sqlxFilter = path: _type: builtins.match ".*\\.sqlx/.*\\.json$" path != null;
        pdfiumFilter = path: _type: builtins.match ".*pdfium-lib/.*\\.(so|dylib)$" path != null;
        assetFilter = path: _type: builtins.match ".*\\.(md|html|txt|json|canvas|sql)$" path != null;
        binFilter = path: _type: builtins.match ".*\\.bin$" path != null;
        srcFilter =
          path: type:
          (sqlxFilter path type)
          || (pdfiumFilter path type)
          || (assetFilter path type)
          || (binFilter path type)
          || (craneLib.filterCargoSources path type);
        cloudStorageSrc = pkgs.lib.cleanSourceWith {
          src = ./rust/cloud-storage;
          filter = srcFilter;
        };
        cSourceFilter = path: _type: builtins.match ".*\\.(c|h)$" path != null;
        libreofficeBindingsSrc = pkgs.lib.cleanSourceWith {
          src = rs-libreoffice-bindings;
          filter = path: type: (cSourceFilter path type) || (craneLib.filterCargoSources path type);
        };
        src = pkgs.runCommand "cloud-storage-src" { } ''
          cp -rT ${cloudStorageSrc} $out
          chmod -R +w $out
          cp -rT ${libreofficeBindingsSrc} $out/rs-libreoffice-bindings
        '';

        # ── Per-artifact pruned deploy sources ────────────────────────
        # .github/workspace-dep-closures.json (generated by `just hakari` via
        # rust/cloud-storage/tools/xtask, drift-checked in CI) maps every workspace
        # crate to its transitive workspace dependency
        # closure. Each deploy leaf builds from a tree where only the crates in
        # its closure keep real sources; every other member is reduced to its
        # manifest plus a crane stub target. A leaf's store hash then only
        # moves when a crate it actually depends on changes — an email-only
        # change leaves the other deploy derivations as pure substitutions
        # (sticky disk / Cachix) instead of full workspace-subgraph rebuilds.
        # Manifest or Cargo.lock changes still invalidate every leaf (the stub
        # layer embeds them all); those are the rare structural commits.
        #
        # Soundness: a stale map fails loud, not silent. A missing closure
        # crate means its stub (empty lib) gets compiled and the dependent
        # crate fails to resolve its items; a deleted dir fails at eval. CI
        # regenerates the map and rejects drift before merge.
        workspaceDepClosures =
          (builtins.fromJSON (builtins.readFile ./.github/workspace-dep-closures.json)).closures;

        # Manifests + Cargo.lock + stub targets for every member, shared by all
        # pruned sources; only changes when a manifest or the lock changes.
        deployDummySrc = craneLib.mkDummySrc { inherit src; };

        # Real sources of one workspace crate dir, same filter as the full tree
        # (keeps per-crate assets: pdfium blobs, .sql migrations, templates).
        crateDirSrc =
          dir:
          pkgs.lib.cleanSourceWith {
            src = ./rust/cloud-storage + "/${dir}";
            filter = srcFilter;
            name = "crate-${builtins.replaceStrings [ "/" ] [ "-" ] dir}";
          };

        # Workspace-root files that crates read across crate boundaries: the
        # .sqlx offline cache (sqlx macros resolve it from the workspace root)
        # and loose root assets like markdown-golden.1.bin (include_bytes!-ed
        # from the documents crate). Included in every pruned source, so a
        # sqlx prepare still invalidates all leaves — coarser than ideal, but
        # the query-to-crate mapping is not recoverable from the file names.
        rootDepsSrc = pkgs.lib.cleanSourceWith {
          src = ./rust/cloud-storage;
          name = "cloud-storage-root-deps";
          filter =
            path: type:
            let
              rel = pkgs.lib.removePrefix ((toString ./rust/cloud-storage) + "/") (toString path);
            in
            (rel == ".sqlx")
            || (pkgs.lib.hasPrefix ".sqlx/" rel)
            || (
              type == "regular"
              && !(pkgs.lib.hasInfix "/" rel)
              && ((assetFilter path type) || (binFilter path type))
            );
        };

        prunedDeploySrc =
          pname: rootPackage:
          let
            # Generator emits dirs sorted, so parents always precede nested
            # members and overlays land inside already-materialised parents.
            dirs =
              workspaceDepClosures.${rootPackage} or (throw (
                "No '${rootPackage}' entry in .github/workspace-dep-closures.json; "
                + "run `just hakari` from rust/cloud-storage and commit the result."
              ));
            overlays = pkgs.lib.concatMapStrings (dir: ''
              rm -rf "$out/${dir}"
              cp -rT ${crateDirSrc dir} "$out/${dir}"
              chmod -R +w "$out/${dir}"
            '') dirs;
          in
          pkgs.runCommand "cloud-storage-src-${pname}" { } ''
            cp -rT ${deployDummySrc} $out
            chmod -R +w $out
            cp -rfT ${rootDepsSrc} $out
            chmod -R +w $out
            ${overlays}
            rm -rf $out/rs-libreoffice-bindings
            cp -rT ${libreofficeBindingsSrc} $out/rs-libreoffice-bindings
          '';

        commonArgs = {
          inherit src;
          pname = "cloud-storage";
          version = "0.1.0";
          strictDeps = true;
          buildInputs = libraries;
          nativeBuildInputs = with pkgs; [ pkg-config ] ++ pkgs.lib.optionals isLinux [ mold ];
          LIBCLANG_PATH = "${pkgs.libclang.lib}/lib";
          OPENSSL_NO_VENDOR = "1";
          SQLX_OFFLINE = "true";
          RUSTFLAGS = pkgs.lib.optionalString isLinux "-C link-arg=-fuse-ld=mold";
          # Build deps + workspace + bins in dev profile so the test job (which runs
          # `cargo nextest` outside the sandbox using the test profile, inheriting dev)
          # can reuse the restored target/debug/ instead of recompiling all deps.
          CARGO_PROFILE = "dev";
        }
        // pkgs.lib.optionalAttrs isLinux {
          LD_LIBRARY_PATH = "${pkgs.lib.makeLibraryPath libraries}";
          BINDGEN_EXTRA_CLANG_ARGS = "-I${pkgs.glibc.dev}/include -I${pkgs.gcc.cc}/lib/gcc/${pkgs.stdenv.hostPlatform.config}/${pkgs.gcc.version}/include";
        };

        # Pre-built third-party deps — Cachix caches this; hash is driven by Cargo.lock
        # (workspace member sources are stubbed by crane), so it survives most PRs.
        # --all-features matches the test job (cargo nextest --all-features) and clippy
        # so all consumers share the same dep feature unification.
        cargoArtifacts = craneLib.buildDepsOnly (
          commonArgs
          // {
            cargoExtraArgs = "--locked --all-features";
          }
        );

        # Layered atop cargoArtifacts: pre-compile every workspace lib crate so
        # downstream derivations (openApiBins, clippy) inherit a warm target/. The
        # hash is per-source so cachix only hits when the SHA matches across CI
        # workflows — but since code-check-cloud-storage and web-app-check-main both
        # run on the same SHA, whichever finishes first pushes for the other.
        workspaceArtifacts = craneLib.cargoBuild (
          commonArgs
          // {
            inherit cargoArtifacts;
            pname = "cloud-storage-workspace";
            doCheck = false;
            doInstallCargoArtifacts = true;
            cargoExtraArgs = "--locked --all-features --workspace --lib";
            RUSTFLAGS = "-Dwarnings" + pkgs.lib.optionalString isLinux " -C link-arg=-fuse-ld=mold";
            RUSTDOCFLAGS = "-Dwarnings";
          }
        );

        openApiBins = craneLib.buildPackage (
          commonArgs
          // {
            cargoArtifacts = workspaceArtifacts;
            pname = "cloud-storage-openapi";
            doCheck = false;
            cargoExtraArgs = pkgs.lib.concatStringsSep " " [
              "--locked"
              "--all-features"
              "--bin document_storage_service_openapi"
              "--bin properties_service_openapi"
              "--bin document_cognition_service_openapi"
              "--bin authentication_service_openapi"
              "--bin notification_service_openapi"
              "--bin static_file_service_openapi"
              "--bin connection_gateway_openapi"
              "--bin contacts_service_openapi"
              "--bin unfurl_service_openapi"
              "--bin email_service_openapi"
              "--bin search_service_openapi"
              "--bin scheduled_action_openapi"
              "--bin document_cognition_service_models"
              "--bin gen_tool_schemas"
            ];
          }
        );

        # Pre-built nextest archive — packages all compiled test binaries plus their
        # metadata into a single tar.zst. CI fetches this archive and runs
        # `cargo nextest run --archive-file` outside the sandbox so tests can hit
        # postgres/redis services. Built in nix → cached by cachix.
        nextestArchive = craneLib.mkCargoDerivation (
          commonArgs
          // {
            cargoArtifacts = workspaceArtifacts;
            pname = "cloud-storage-nextest-archive";
            doCheck = false;
            nativeBuildInputs = commonArgs.nativeBuildInputs or [ ] ++ [ pkgs.cargo-nextest ];
            buildPhaseCargoCommand = ''
              cargo nextest archive \
                --cargo-profile dev \
                --locked --all-features \
                --workspace --lib --bins --tests \
                --archive-file nextest-archive.tar.zst
            '';
            installPhaseCommand = ''
              mkdir -p $out
              cp nextest-archive.tar.zst $out/
            '';
          }
        );

        deployServiceBinaryDefinitions = [
          {
            serviceName = "agent-schedule-service";
            packageName = "scheduled_action";
            binaries = [ "service" ];
          }
          {
            serviceName = "authentication-service";
            packageName = "authentication_service";
            binaries = [ "authentication_service" ];
          }
          {
            serviceName = "connection-gateway";
            packageName = "connection_gateway";
            binaries = [ "connection_gateway_service" ];
          }
          {
            serviceName = "contacts-service";
            packageName = "contacts_service";
            binaries = [ "contacts_service" ];
          }
          {
            serviceName = "convert-service";
            packageName = "convert_service";
            binaries = [ "convert_service" ];
          }
          {
            serviceName = "document-cognition-service";
            packageName = "document_cognition_service";
            binaries = [ "document_cognition_service" ];
          }
          {
            serviceName = "document-storage-service";
            packageName = "document_storage_service";
            binaries = [ "document_storage_service" ];
          }
          {
            serviceName = "email-service";
            packageName = "email_service";
            binaries = [
              "email_service"
              "pubsub_workers"
            ];
          }
          {
            serviceName = "image-proxy-service";
            packageName = "image_proxy_service";
            binaries = [ "image_proxy_service" ];
          }
          {
            serviceName = "mcp-server";
            packageName = "mcp_service";
            binaries = [ "mcp_service" ];
          }
          {
            serviceName = "notification-service";
            packageName = "notification_service";
            binaries = [ "notification_service" ];
          }
          {
            serviceName = "search-processing-service";
            packageName = "search_processing_service";
            binaries = [ "search_processing_service" ];
          }
          {
            serviceName = "static-file-service";
            packageName = "static_file_service";
            binaries = [ "static_file_service" ];
          }
          {
            serviceName = "unfurl-service";
            packageName = "unfurl_service";
            binaries = [ "unfurl_service" ];
          }
        ];

        deployBinaryCargoExtraArgs =
          "--locked "
          + pkgs.lib.concatMapStringsSep " " (
            def:
            "--package ${def.packageName} "
            + pkgs.lib.concatMapStringsSep " " (binary: "--bin ${binary}") def.binaries
          ) deployServiceBinaryDefinitions;

        deployCargoArtifacts = craneLib.buildDepsOnly (
          commonArgs
          // {
            pname = "cloud-storage-deploy-deps";
            doCheck = false;
            # buildDepsOnly runs a cargo check in buildPhase by default; keep this
            # warm artifact to release deps only.
            cargoCheckCommand = "true";
            cargoExtraArgs = deployBinaryCargoExtraArgs;
            CARGO_PROFILE = "release";
          }
        );

        deployServiceBinaryPackage =
          {
            serviceName,
            packageName,
            binaries,
          }:
          craneLib.buildPackage (
            commonArgs
            // {
              # Pruned source: this derivation only rebuilds when a crate in
              # the service's own workspace closure changes.
              src = prunedDeploySrc "service-${serviceName}" packageName;
              cargoArtifacts = deployCargoArtifacts;
              pname = "cloud-storage-${serviceName}-binaries";
              doCheck = false;
              cargoExtraArgs =
                "--locked --package ${packageName} "
                + pkgs.lib.concatMapStringsSep " " (binary: "--bin ${binary}") binaries;
              CARGO_PROFILE = "release";
              installPhaseCommand = ''
                mkdir -p $out/bin
                for binary in ${pkgs.lib.concatStringsSep " " binaries}; do
                  cp target/release/$binary $out/bin/$binary
                  ${pkgs.binutils}/bin/strip $out/bin/$binary || true
                done
              '';
            }
          );

        deployServiceBinaryPackages = pkgs.lib.listToAttrs (
          map (def: {
            name = "deploy-service-binaries-${def.serviceName}";
            value = deployServiceBinaryPackage def;
          }) deployServiceBinaryDefinitions
        );

        # ── Lambda builds (crane + cargo-zigbuild) ─────────────────────
        # SPIKE: build a Rust Lambda handler reproducibly under nix/crane so
        # lambdas ride the same content-addressed cache as the service binaries
        # (nix store + Cachix + sticky disk) instead of a cargo-in-checkout that
        # recompiles the workspace every run. cargo-zigbuild pins the Lambda
        # glibc via a target *suffix* (no toolchain swap; host triple == lambda
        # triple, so no extra rust-std). The binary is renamed `bootstrap` and
        # zipped for the provided.al2/al2023 custom runtime.
        lambdaTarget = "x86_64-unknown-linux-gnu";
        # glibc 2.26 == Amazon Linux 2; forward-compatible with al2023.
        lambdaZigTarget = "${lambdaTarget}.2.26";

        callRecordingPreviewFfmpegLayer =
          let
            ffmpegVersion = "7.0.2";
            ffmpegArchive = pkgs.fetchurl {
              url = "https://johnvansickle.com/ffmpeg/releases/ffmpeg-${ffmpegVersion}-amd64-static.tar.xz";
              hash = "sha256-q9qNd86DCRQfg6uO3wWWg0CHxSRn9rrfN2pqKkyHz2c=";
            };
          in
          pkgs.runCommand "call-recording-preview-ffmpeg-layer"
            {
              nativeBuildInputs = [
                pkgs.coreutils
                pkgs.gnutar
                pkgs.unzip
                pkgs.xz
                pkgs.zip
              ];
            }
            ''
              set -euo pipefail

              archive_dir="ffmpeg-${ffmpegVersion}-amd64-static"
              mkdir -p extract package/bin "$out/call_recording_preview_handler"
              tar -xJf ${ffmpegArchive} -C extract \
                "$archive_dir/ffmpeg" \
                "$archive_dir/ffprobe"
              install -m 0755 "extract/$archive_dir/ffmpeg" package/bin/ffmpeg
              install -m 0755 "extract/$archive_dir/ffprobe" package/bin/ffprobe
              touch -h -d @315532800 package/bin/ffmpeg package/bin/ffprobe

              (
                cd package
                zip -9 -q -X "$out/call_recording_preview_handler/ffmpeg-layer.zip" bin/ffmpeg bin/ffprobe
              )
              unzip -tqq "$out/call_recording_preview_handler/ffmpeg-layer.zip" >/dev/null
            '';

        lambdaCommonArgs = commonArgs // {
          # zig links the final binary (cargo-zigbuild); drop the host-only mold arg.
          RUSTFLAGS = "";
          CARGO_PROFILE = "release";
          # Lambdas don't need max opt; matches the cargo-lambda CI setting.
          CARGO_PROFILE_RELEASE_OPT_LEVEL = "2";
          # aws-lc-sys (aws-lc-rs / rustls default crypto, pulled via aws-sdk &
          # sqlx) has a cc-builder guard that rejects the zig C compiler. Force
          # its cmake builder instead, which has no such guard and still compiles
          # the C against the zig-pinned glibc. cmake + nasm are its build deps.
          AWS_LC_SYS_CMAKE_BUILDER = "1";
          nativeBuildInputs = (commonArgs.nativeBuildInputs or [ ]) ++ [
            pkgs.cargo-zigbuild
            pkgs.zig
            pkgs.cmake
            pkgs.nasm
          ];
          # zig needs a writable cache inside the sandbox ($HOME is read-only).
          preBuild = ''
            export ZIG_GLOBAL_CACHE_DIR="$TMPDIR/zig-cache"
            export ZIG_LOCAL_CACHE_DIR="$TMPDIR/zig-cache"
            export XDG_CACHE_HOME="$TMPDIR/xdg"

            # Inherited cargoArtifacts can carry CMake configure state
            # (CMakeCache.txt / CMakeFiles) from the deps-only layer. Its
            # CMAKE_C_COMPILER points at a cargo-zigbuild wrapper script under
            # $TMPDIR whose hash-suffixed name need not exist in this sandbox,
            # and CMake hard-fails validating a cached compiler that is gone
            # ("is not a full path to an existing compiler tool"). Drop the
            # configure state so a build-script re-run reconfigures cleanly;
            # crates whose fingerprints are clean never read it, so this costs
            # nothing on the cached path. (Today aws-lc-sys is the only cmake
            # crate in the graph, via AWS_LC_SYS_CMAKE_BUILDER below.)
            tdir="''${CARGO_TARGET_DIR:-target}"
            if [ -d "$tdir" ]; then
              while IFS= read -r -d "" cache; do
                dir="$(dirname "$cache")"
                echo "purging stale cmake configure state in $dir"
                rm -rf "$dir/CMakeFiles" "$cache"
              done < <(find "$tdir" -name CMakeCache.txt -print0)
            fi
          '';
        };

        # Every handler deployed as a lambda, read straight from the deploy
        # config so the flake never drifts from services-config.json. For every
        # handler, crate name == dir name == deploy_lambdas entry.
        lambdaNames =
          let
            cfg = builtins.fromJSON (builtins.readFile ./.github/services-config.json);
          in
          pkgs.lib.unique (
            pkgs.lib.concatMap (svc: svc.deploy_lambdas or [ ]) (pkgs.lib.attrValues cfg.services)
          );

        # One shared dep closure for all lambda handlers. Build it with the same
        # cargo-zigbuild target used by the final packages; Cargo fingerprints the
        # `.2.26` target separately from the plain triple, so warming the plain
        # target does not help the deploy builds.
        lambdaDeployCargoArtifacts = craneLib.buildDepsOnly (
          lambdaCommonArgs
          // {
            pname = "cloud-storage-lambda-deps";
            doCheck = false;
            # buildDepsOnly runs a cargo check in buildPhase by default; keep this
            # warm artifact to release deps only.
            cargoCheckCommand = "true";
            cargoBuildCommand = "cargo zigbuild --release";
            cargoExtraArgs =
              "--locked --target ${lambdaZigTarget} "
              + pkgs.lib.concatMapStringsSep " " (n: "--package ${n}") lambdaNames;
          }
        );

        # bin name == crate name == handler dir name (see per-lambda justfiles).
        deployLambdaPackage =
          lambdaName:
          craneLib.buildPackage (
            lambdaCommonArgs
            // {
              # Pruned source: this derivation only rebuilds when a crate in
              # the handler's own workspace closure changes.
              src = prunedDeploySrc "lambda-${lambdaName}" lambdaName;
              cargoArtifacts = lambdaDeployCargoArtifacts;
              pname = "cloud-storage-lambda-${lambdaName}";
              doCheck = false;
              # cargo-zigbuild links the final binary against the pinned Lambda
              # glibc, selected via the `.2.26` target suffix.
              cargoBuildCommand = "cargo zigbuild --release";
              cargoExtraArgs = "--locked --target ${lambdaZigTarget} --bin ${lambdaName}";
              # Emit the Lambda custom-runtime artifact: a zip whose single entry
              # is named `bootstrap`, mirroring cargo-lambda's
              # target/lambda/<name>/bootstrap.zip layout. zigbuild writes to
              # target/<triple>/release (suffix stripped from the dir name).
              installPhaseCommand = ''
                mkdir -p "$out/${lambdaName}"
                cp "target/${lambdaTarget}/release/${lambdaName}" bootstrap
                ${pkgs.binutils}/bin/strip bootstrap || true
                ${pkgs.zip}/bin/zip -j -X "$out/${lambdaName}/bootstrap.zip" bootstrap
                ${pkgs.lib.optionalString (lambdaName == "call_recording_preview_handler") ''
                  cp "${callRecordingPreviewFfmpegLayer}/${lambdaName}/ffmpeg-layer.zip" "$out/${lambdaName}/ffmpeg-layer.zip"
                ''}
              '';
            }
          );

        deployLambdaPackages = pkgs.lib.listToAttrs (
          map (n: {
            name = "deploy-lambda-${n}";
            value = deployLambdaPackage n;
          }) lambdaNames
        );

        shellTools =
          with pkgs;
          [
            parallel
            docker-compose
            curl
            xz
            unzip
            zip
            cargo-info
            cargo-udeps
            cargo-lambda
            cargo-zigbuild
            zig
            cmake
            nasm
            (writeShellScriptBin "rustup" ''
              set -euo pipefail
              rustc_path="$(${coreutils}/bin/readlink -f "$(command -v rustc)")"
              toolchain="$(${coreutils}/bin/basename "$(${coreutils}/bin/dirname "$(${coreutils}/bin/dirname "$rustc_path")")")"
              case "$1 $2" in
                "toolchain list") echo "$toolchain (default)" ;;
                "toolchain add") exit 0 ;;
                "target list") echo "x86_64-unknown-linux-gnu (installed)"; echo "aarch64-unknown-linux-gnu"; echo "wasm32-unknown-unknown (installed)" ;;
                "target add") exit 0 ;;
                "component list") echo "rust-src-x86_64-unknown-linux-gnu (installed)"; echo "clippy-x86_64-unknown-linux-gnu (installed)" ;;
                "component add") exit 0 ;;
                *) echo "rustup shim only supports commands used by cross" >&2; exit 1 ;;
              esac
            '')
            cargo-cross
            cargo-deny
            cargo-nextest
            cargo-expand
            wasm-pack
            pkg-config
            bacon
            just
            just-lsp
            taplo
            bun
            pnpm
            sqlx-cli
            typescript-language-server
            nodejs_24
            pulumi
            pulumiPackages.pulumi-nodejs
            sops
            biome
            jq
            stripe-cli
            sccache
            rustToolchain
          ]
          ++ pkgs.lib.optionals isLinux [ mold ];

        # ── js-app (frontend Tauri app) ────────────────────────────────

        # Need allowUnfree + android license for the Android SDK
        jsPkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
          config.android_sdk.accept_license = true;
        };

        android_sdk = pkgs.lib.optionalAttrs isLinux (
          (jsPkgs.androidenv.composeAndroidPackages {
            platformVersions = [
              "34"
              "36"
            ];
            buildToolsVersions = [
              "35.0.0"
            ];
            ndkVersions = [ "26.3.11579264" ];
            includeNDK = true;
            useGoogleAPIs = false;
            useGoogleTVAddOns = false;
            includeEmulator = true;
            includeSystemImages = true;
            systemImageTypes = [ "google_apis_playstore" ];
            abiVersions = [ "x86_64" ];
            includeSources = false;
          }).androidsdk
        );

        jsBasePackages = with jsPkgs; [
          curl
          wget
          pkg-config
          just
          bun
          biome
          nodejs_24
          typescript-language-server
          cargo-tauri
          cargo-info
          cargo-udeps
          pulumi
          pulumiPackages.pulumi-nodejs
          pulumiPackages.pulumi-aws-native
          playwright
          playwright-mcp
          (
            with fenix.packages.${system};
            combine (
              [
                complete.rustc
                complete.rust-src
                complete.cargo
                complete.clippy
                complete.rustfmt
                complete.rust-analyzer
              ]
              ++ pkgs.lib.optionals isLinux [
                targets.aarch64-linux-android.latest.rust-std
                targets.armv7-linux-androideabi.latest.rust-std
                targets.i686-linux-android.latest.rust-std
                targets.x86_64-linux-android.latest.rust-std
              ]
            )
          )
        ];

        jsLinuxPackages = with jsPkgs; [
          gst_all_1.gstreamer
          gst_all_1.gst-plugins-base
          gst_all_1.gst-plugins-good
          gst_all_1.gst-plugins-bad
          jdk
          xdg-utils
        ];

        jsPackages = jsBasePackages ++ pkgs.lib.optionals isLinux (jsLinuxPackages ++ [ android_sdk ]);

        jsLinuxLibraries = with jsPkgs; [
          gtk3
          libsoup_3
          webkitgtk_4_1
          cairo
          gdk-pixbuf
          glib
          dbus
          openssl
          librsvg
          lsb-release
        ];

        jsDarwinLibraries = with jsPkgs; [
          openssl
          libiconv
        ];

        jsLibraries = if isDarwin then jsDarwinLibraries else jsLinuxLibraries;
      in
      {
        checks = {
          fmt = craneLib.cargoFmt {
            inherit src;
            pname = "cloud-storage";
            version = "0.1.0";
          };
          clippy = craneLib.cargoClippy (
            commonArgs
            // {
              cargoArtifacts = workspaceArtifacts;
              cargoClippyExtraArgs = "--all-features -- -D warnings";
              RUSTDOCFLAGS = "-Dwarnings";
            }
          );
          gen-api =
            let
              openApiFiles = pkgs.lib.cleanSourceWith {
                src = ./js/app/packages/service-clients;
                filter = path: type: type == "directory" || pkgs.lib.hasSuffix "openapi.json" (baseNameOf path);
              };
              crateToDir = {
                document_storage_service = "service-storage";
                properties_service = "service-properties";
                document_cognition_service = "service-cognition";
                authentication_service = "service-auth";
                notification_service = "service-notification";
                static_file_service = "service-static-files";
                connection_gateway = "service-connection";
                contacts_service = "service-contacts";
                unfurl_service = "service-unfurl";
                email_service = "service-email";
                search_service = "service-search";
                scheduled_action = "service-scheduled-action";
              };
              checkScript = pkgs.lib.concatStringsSep "\n" (
                pkgs.lib.mapAttrsToList (crate: dir: ''
                  echo -n "Checking ${dir}/openapi.json ... "
                  if ! diff \
                    <("${openApiBins}/bin/${crate}_openapi" | ${pkgs.jq}/bin/jq --sort-keys .) \
                    <(${pkgs.jq}/bin/jq --sort-keys . < "${openApiFiles}/${dir}/openapi.json"); then
                    echo "FAIL: run 'bun run gen-api' and commit the result"
                    exit 1
                  fi
                  echo "ok"
                '') crateToDir
              );
            in
            pkgs.runCommand "cloud-storage-gen-api-check" { RUST_LOG = "error"; } ''
              ${checkScript}
              touch $out
            '';
        };

        packages = {
          inherit
            cargoArtifacts
            callRecordingPreviewFfmpegLayer
            workspaceArtifacts
            deployCargoArtifacts
            lambdaDeployCargoArtifacts
            openApiBins
            nextestArchive
            ;
          default = cargoArtifacts;
        }
        // deployServiceBinaryPackages
        // deployLambdaPackages;

        devShells = {
          default = pkgs.mkShell (
            {
              buildInputs = shellTools ++ libraries;
              PKG_CONFIG_PATH = "${pkgs.openssl.dev}/lib/pkgconfig";
              LIBCLANG_PATH = "${pkgs.libclang.lib}/lib";
              SOPS_KMS_ARN = "arn:aws:kms:us-east-1:569036502058:key/mrk-cab29bf948044eb79005a81f48d40e93,arn:aws:kms:us-west-1:569036502058:key/mrk-cab29bf948044eb79005a81f48d40e93";
              RUSTC_WRAPPER = "${pkgs.sccache}/bin/sccache";
              # Keep local cargo-lambda builds on the same aws-lc-sys path as
              # the Nix lambda derivations. The default cc builder rejects
              # cargo-lambda/cargo-zigbuild's Zig cc wrapper.
              AWS_LC_SYS_CMAKE_BUILDER = "1";
            }
            // pkgs.lib.optionalAttrs isLinux {
              LD_LIBRARY_PATH = "${pkgs.lib.makeLibraryPath libraries}";
              BINDGEN_EXTRA_CLANG_ARGS = "-I${pkgs.glibc.dev}/include -I${pkgs.gcc.cc}/lib/gcc/${pkgs.stdenv.hostPlatform.config}/${pkgs.gcc.version}/include";
            }
          );

          js-app = jsPkgs.mkShell (
            {
              buildInputs = jsPackages ++ jsLibraries;
              PKG_CONFIG_PATH = "${jsPkgs.openssl.dev}/lib/pkgconfig";
            }
            // pkgs.lib.optionalAttrs isLinux {
              LD_LIBRARY_PATH = "${pkgs.lib.makeLibraryPath jsLibraries}:$LD_LIBRARY_PATH";
              XDG_DATA_DIRS = "${jsPkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${jsPkgs.gsettings-desktop-schemas.name}:${jsPkgs.gtk3}/share/gsettings-schemas/${jsPkgs.gtk3.name}:$XDG_DATA_DIRS";
              ANDROID_HOME = "${android_sdk}/libexec/android-sdk";
              NDK_HOME = "${android_sdk}/libexec/android-sdk/ndk/26.3.11579264";
              GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${android_sdk}/libexec/android-sdk/build-tools/35.0.0/aapt2";
              GIO_MODULE_DIR = "${jsPkgs.glib-networking}/lib/gio/modules/";
            }
          );
        };
      }
    );
}
