//! Local-only public-origin admission. Workers receive configuration through
//! bindings, not process environment (LOCAL_PUBLIC_ORIGIN is generated by xtask).

pub(super) fn is_allowed(origin: &str, environment: &str, configured: Option<&str>) -> bool {
    if environment != "local" {
        return false;
    }
    let Some(configured) = configured else {
        return false;
    };
    let Ok(url) = worker::Url::parse(configured) else {
        return false;
    };
    url.scheme() == "https"
        && url.username().is_empty()
        && url.password().is_none()
        && url.path() == "/"
        && url.query().is_none()
        && url.fragment().is_none()
        && url.origin().ascii_serialization() == configured
        && origin == configured
}

#[cfg(test)]
mod test;
