[workspace]
members = [
  "input_accessory_plugin",
  "logger",
  "macro_bundle_updater_plugin",
  "navigation_plugin",
  "src-tauri",
]
package.edition = "2024"
resolver = "2"

[workspace.dependencies]
reqwest = "0.13"
rootcause = "0.12"
semver = "1"
serde = "1"
tauri = { path = "/home/sean/dev/tauri/crates/tauri" }
thiserror = "2"
tokio = "1"
tracing = "0.1"
url = "2.5.4"

[patch.crates-io]
tauri = { path = "/home/sean/dev/tauri/crates/tauri" }
tauri-runtime = { path = "/home/sean/dev/tauri/crates/tauri-runtime" }
tauri-runtime-wry = { path = "/home/sean/dev/tauri/crates/tauri-runtime-wry" }
tauri-utils = { path = "/home/sean/dev/tauri/crates/tauri-utils" }
tauri-macros = { path = "/home/sean/dev/tauri/crates/tauri-macros" }
tauri-codegen = { path = "/home/sean/dev/tauri/crates/tauri-codegen" }
tauri-build = { path = "/home/sean/dev/tauri/crates/tauri-build" }
