//! `cargo workspace dependency check` — polices duplicate third-party deps in
//! human-written crates, and rejects drift in the generated workspace-hack +
//! dep-closure map. Generated into `cargo_workspace_dependency_check.yml`
//! (replaces the hand-written `cargo-workspace-dependency-check.yml`).
//!
//! Both jobs build Rust, so they run on the rust-ci profile with the Nix/Cargo
//! cache volume and Namespace's shared `sccache-ci` remote cache. This replaces
//! the deprecated `actions-rs/toolchain` + hardcoded `rustup default 1.85`
//! (which drifted from the workspace toolchain) and gives the `cargo install`
//! and xtask builds warm caches instead of compiling cold on every run.

use gh_workflow::{
    Concurrency, Event, Expression, Job, PullRequest, PullRequestType, Run, Step, Use, Workflow,
};

use crate::workflows::{runners, steps, vars};

/// Build the workflow.
pub fn cargo_workspace_dependency_check() -> Workflow {
    Workflow::new("cargo workspace dependency check")
        .on(Event::default().pull_request(
            PullRequest::default()
                .add_branch("main")
                .add_type(PullRequestType::Opened)
                .add_type(PullRequestType::Synchronize)
                .add_type(PullRequestType::Reopened)
                .add_type(PullRequestType::ReadyForReview)
                .add_path(xtask_paths::repo_glob!("Cargo.toml"))
                .add_path(xtask_paths::repo_glob!("crates/**/Cargo.toml"))
                .add_path(xtask_paths::repo_glob!("services/**/Cargo.toml"))
                .add_path(xtask_paths::repo_glob!("tooling/xtask/**/Cargo.toml"))
                .add_path(xtask_paths::repo_glob!("Cargo.lock"))
                .add_path(xtask_paths::repo_glob!(".config/hakari.toml"))
                .add_path(xtask_paths::repo_glob!("crates/workspace-hack/**"))
                // Source of `cargo x deps` only — not every xtask crate. A
                // nextest-filter or workflow-generator edit cannot drift the
                // hack crate or closure map.
                .add_path(xtask_paths::repo_glob!("tooling/xtask/src/**"))
                .add_path(xtask_paths::repo_glob!(
                    "tooling/xtask/crates/xtask_deps/**"
                ))
                .add_path(xtask_paths::repo_glob!(
                    "tooling/xtask/crates/xtask_graph/**"
                ))
                .add_path(xtask_paths::repo_glob!(
                    ".github/workspace-dep-closures.json"
                )),
        ))
        .concurrency(
            Concurrency::new(Expression::new(
                "cargo-workspace-dependency-check-${{ github.ref }}",
            ))
            .cancel_in_progress(true),
        )
        .add_job("dependency-check", dependency_check())
        .add_job("hakari-and-dep-closures", hakari_and_dep_closures())
}

fn rust_ci_job() -> Job {
    Job::default()
        .runs_on(runners::Runner::RustCi.with_cache_tag(vars::CI_CACHE_TAG))
        .add_step(checkout())
        .add_step(steps::mount_cache_volume())
        .add_step(steps::setup_nix())
        .add_step(steps::setup_dev_shell())
        .add_step(steps::configure_namespace_sccache(vars::CI_SCCACHE_NAME))
}

fn dependency_check() -> Job {
    rust_ci_job()
        .add_step(install_checker())
        .add_step(run_checker())
        .add_step(steps::teardown_nix())
}

/// The workspace-hack crate pins every third-party dep to its union feature
/// set so a solo `cargo build -p <crate>` resolves identical features to the
/// union-built crane dep layers (deployCargoArtifacts /
/// lambdaDeployCargoArtifacts) — without it, per-service/per-lambda CI builds
/// silently recompile shared deps. The closure map drives the pruned
/// per-artifact deploy sources in flake.nix. Both are generated by the
/// lock-pinned engine in tooling/xtask; this job rejects
/// drift. Regenerate locally with `just hakari` from the repository root.
fn hakari_and_dep_closures() -> Job {
    rust_ci_job()
        .add_step(deps_check())
        .add_step(steps::teardown_nix())
}

fn checkout() -> Step<Use> {
    Step::new("Checkout Repo").uses(
        "actions",
        "checkout",
        "df4cb1c069e1874edd31b4311f1884172cec0e10",
    ) // v6
}

/// `cargo install` skips the build when the same version is already present
/// in `~/.cargo/bin` (persisted on the cache volume); cold installs compile
/// through Namespace's remote sccache.
fn install_checker() -> Step<Run> {
    Step::new("install tool").run("cargo install cargo-workspace-dependency-checker@1.0.1")
}

fn run_checker() -> Step<Run> {
    Step::new("check").run(indoc::indoc! {r#"
        # workspace-hack (generated, see xtask) re-declares third-party deps
        # with explicit versions by design — that is how it pins union
        # features. Drop it from the member list so this check only polices
        # human-written crates for duplicate dependencies.
        sed -i '/^  "crates\/workspace-hack",$/d' Cargo.toml
        cargo-workspace-dependency-checker
    "#})
}

fn deps_check() -> Step<Run> {
    Step::new("generated dependency artifacts are up to date").run(indoc::indoc! {r#"
        cargo run -p xtask --locked -- deps --check
    "#})
}
