[package]
description = "xtask nextest-filter: affected Cargo packages for a set of changed files"
edition = "2024"
name = "xtask_nextest_filter"
publish = false
version = "0.1.0"

[[bin]]
name = "xtask_nextest_filter"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
determinator = { workspace = true }
guppy = { workspace = true }
tempfile = { workspace = true }
xtask_graph = { path = "../xtask_graph" }
xtask_paths = { path = "../xtask_paths" }
