config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  organization-service:datadog_api_key:
    secure: AAABAAboYfBaOy3paj+BjyJpdPuoFkIyWUYTmIGmTeeDVN2eLymWEb+5M5S8SYXRmOG6cga2zDRzYmfoEUxhYQ==
  organization-service:document_storage_service_auth_key: document-storage-service-auth-key-dev
  organization-service:legacy_jwt_secret_key: jwt-secret-dev
  organization-service:macro_db_secret_key: macro-db-dev
  organization-service:macro_cache_secret_key: macro-cache-dev
  organization-service:jwt_secret_key: fusionauth-jwt-secret-dev
  organization-service:fusionauth_client_id: eb75fe7a-0ef1-4186-96d9-cc62cfb1d10c
  organization-service:fusionauth_issuer: fusionauth-dev.macro.com
  organization-service:authentication_service_internal_api_key: authentication-service-internal-api-key-dev
