config:
  aws:region: us-east-1
  aws-native:region: us-east-1
  preview-gateway:preview_domain: macro-agent-gateway.com
  preview-gateway:preview_zone_id: Z02409452IBB8642CNAGC
  doppler:dopplerToken:
    secure: AAABAIShlLbr8nqVYhy6UMCE3fgXfBvrP+GCeAZnJEUnC+ffIHawkVAO82TXEyBsEv/mb2fQpyfUX1sVFPxsyYoU4pX+IXuagq32n91k2rsf
