[package]
edition = "2024"
name = "item-filter-index"
publish = false
version = "0.1.0"

[dependencies]
filter_ast = { path = "../filter_ast" }
item_filters = { path = "../item_filters", default-features = false }
predicate-index = { path = "../predicate_index" }
thiserror = { workspace = true }
uuid = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { workspace = true, features = ["js"] }

[dev-dependencies]
chrono = { workspace = true }
document_sub_type = { path = "../document_sub_type", default-features = false }
system_properties = { path = "../system_properties" }
