name: app
options:
  bundleIdPrefix: com.macro.app.prod
  deploymentTarget:
    iOS: 14.0
packages:
  CallKitPlugin:
    path: ../../../callkit_plugin/ios
fileGroups: [../../src]
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: macro
      PRODUCT_BUNDLE_IDENTIFIER: com.macro.app.prod
      DEVELOPMENT_TEAM: TY74Q77JBD
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups: [app]
targets:
  app_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Externals
        excludes:
          - "**/*.a"
          - "**/*.framework"
      - path: app_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: app_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64, metal]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 2.0.2
        CFBundleVersion: "142"
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - macro
            CFBundleURLName: macro
        NSUserActivityTypes:
          - INSendMessageIntent
          - NSUserActivityTypeBrowsingWeb
        NSCameraUsageDescription: "This app needs access to the camera to take photos and videos for attachments."
        NSMicrophoneUsageDescription: "This app needs access to the microphone to record videos for attachments."
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to upload attachments."
        LSApplicationQueriesSchemes:
          - macro
        UIBackgroundModes:
          - audio
          - voip
    entitlements:
      path: app_iOS/app_iOS.entitlements
      properties:
        aps-environment: production
        com.apple.developer.associated-domains:
          - applinks:macro.com
          - applinks:dev.macro.com
          - applinks:staging.macro.com
        com.apple.developer.usernotifications.communication: true
        com.apple.developer.usernotifications.time-sensitive: true
        com.apple.security.application-groups:
          - group.com.macro.app.prod
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ENABLE_DEBUG_DYLIB: false
        ARCHS: [arm64]
        VALID_ARCHS: arm64 
        FRAMEWORK_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION)
        FRAMEWORK_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION)
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups: [app]
    dependencies:
      - target: NotificationServiceExtension
        embed: true
      - target: ShareExtension
        embed: true
      - framework: libapp.a
        embed: false
      - package: CallKitPlugin
        product: tauri-plugin-call-kit
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
    preBuildScripts:
      - script: export PATH="$PATH:$HOME/.cargo/bin" && cargo tauri ios xcode-script -v --platform ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?} --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}" --header-search-paths "${HEADER_SEARCH_PATHS:?}" --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}" --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Share to Macro
        CFBundleShortVersionString: 2.0.2
        CFBundleVersion: "142"
        LSApplicationQueriesSchemes:
          - macro
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsImageWithMaxCount: 10
              NSExtensionActivationSupportsMovieWithMaxCount: 5
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.macro.app.prod
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macro.app.prod.ShareExtension
        DEVELOPMENT_TEAM: TY74Q77JBD
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
        ARCHS: [arm64]
        VALID_ARCHS: arm64
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
  NotificationServiceExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: NotificationServiceExtension
    info:
      path: NotificationServiceExtension/Info.plist
      properties:
        CFBundleDisplayName: NotificationServiceExtension
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: "142"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.usernotifications.service
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).NotificationService
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macro.app.prod.NotificationServiceExtension
        DEVELOPMENT_TEAM: TY74Q77JBD
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
        ARCHS: [arm64]
        VALID_ARCHS: arm64
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64