disallowed-methods = [
    { path = "sqlx::query", replacement = "sqlx::query!" },
    { path = "sqlx::query_as", replacement = "sqlx::query_as!" },
    { path = "sqlx::query_scalar", replacement = "sqlx::query_scalar!" },
]
