FROM rust:latest AS builder

WORKDIR /app

ENV SQLX_OFFLINE=true

COPY ./Cargo.lock Cargo.lock
COPY ./Cargo.toml Cargo.toml
COPY . .

RUN --mount=type=cache,id=cargo_build,target=/usr/local/cargo/registry cargo build --release --bin sha_ref_count_resetter

FROM debian:trixie-slim AS runner

# Install ssl certs so we can connect to the DB with ssl true
RUN apt-get update && apt install -y ca-certificates openssl

COPY --from=builder /app/target/release/sha_ref_count_resetter .

CMD ["./sha_ref_count_resetter"]
