MACRODB := "postgres://user:password@localhost:5432/macrodb"
DATABASE_URL := "postgres://user:password@localhost:5432"

check:
    RUSTFLAGS=-Dwarnings RUSTDOCFLAGS=-Dwarnings CARGO_TERM_COLOR=always SQLX_OFFLINE=true cargo check

format:
    SQLX_OFFLINE=true cargo fmt

clean:
    cargo clean
    git restore target/lambda

build:
    SQLX_OFFLINE=true cargo build

# Build all lambda functions
# CARGO_LAMBDA_COMPILER=cargo is needed for NixOS compatibility with aws-lc-sys
build_lambdas:
    #!/usr/bin/env -S parallel --shebang --ungroup --jobs {{ num_cpus() }}
    CARGO_LAMBDA_COMPILER=cargo just docx_unzip_handler/build
    CARGO_LAMBDA_COMPILER=cargo just delete_chat_handler/build
    CARGO_LAMBDA_COMPILER=cargo just organization_retention_handler/build
    CARGO_LAMBDA_COMPILER=cargo just organization_retention_trigger/build
    CARGO_LAMBDA_COMPILER=cargo just upload_extractor_lambda_trigger/build
    CARGO_LAMBDA_COMPILER=cargo just upload_extractor_lambda_handler/build
    CARGO_LAMBDA_COMPILER=cargo just worker_trigger/build
    CARGO_LAMBDA_COMPILER=cargo just dataloss_prevention_handler/build
    CARGO_LAMBDA_COMPILER=cargo just search_upload_handler/build
    CARGO_LAMBDA_COMPILER=cargo just document_text_extractor/build
    CARGO_LAMBDA_COMPILER=cargo just email_suppression_handler/build
    CARGO_LAMBDA_COMPILER=cargo just deleted_item_poller/build
    CARGO_LAMBDA_COMPILER=cargo just email_refresh_handler/build
    CARGO_LAMBDA_COMPILER=cargo just user_link_cleanup_handler/build

# TESTING

# Copies over necessary .env files for sqlx tests
setup_test_envs:
    echo "DATABASE_URL={{ DATABASE_URL }}/notificationdb" >> ./notification_db_client/.env
    echo "DATABASE_URL={{ DATABASE_URL }}/contacts" >> ./contacts_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./properties_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./macro_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./comms_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./document_cognition_service/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./document_text_extractor/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./organization_retention_handler/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./organization_retention_trigger/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./organization_retention_handler/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./sha_cleanup_worker/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./sha_ref_count_resetter/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./roles_and_permissions/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./teams/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./frecency/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./soup/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./system_properties/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./properties/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./name_search/.env

setup_macrodb:
    just macro_db_client/migrate_db
    just document_cognition_service/prepare-test

initialize_dbs: setup_macrodb
    # notificationdb
    just notification_db_client/setup
    # contactsdb
    just contacts_db_client/setup
