MACRODB := "postgres://user:password@localhost:5432/macrodb"
DATABASE_URL := "postgres://user:password@localhost:5432"

mod sqlx './sqlx.just'

check:
    RUSTFLAGS=-Dwarnings RUSTDOCFLAGS=-Dwarnings CARGO_TERM_COLOR=always SQLX_OFFLINE=true cargo check

clippy:
    RUSTFLAGS=-Dwarnings RUSTDOCFLAGS=-Dwarnings CARGO_TERM_COLOR=always SQLX_OFFLINE=true cargo clippy

# This can be used in any crate that uses macrodb under the hood
[no-cd]
prepare_db:
    just sqlx::prepare_db {{ MACRODB }}

format:
    SQLX_OFFLINE=true cargo fmt

clean:
    cargo clean
    git restore target/lambda

build:
    SQLX_OFFLINE=true cargo build

# Build all dev service Docker images (pre-warms cache for run_local_build)
build_dev_service_images:
  docker build -f Dockerfile.dev --target builder -t local-services .
  docker build -f Dockerfile.search_processing_service.dev --target builder -t local-search-processing-service .

# Build all lambda functions
build_lambdas:
    ulimit -n 10240 && just docx_unzip_handler/build
    ulimit -n 10240 && just delete_chat_handler/build
    ulimit -n 10240 && just organization_retention_handler/build
    ulimit -n 10240 && just organization_retention_trigger/build
    ulimit -n 10240 && just upload_extractor_lambda_trigger/build
    ulimit -n 10240 && just upload_extractor_lambda_handler/build
    ulimit -n 10240 && just worker_trigger/build
    ulimit -n 10240 && just dataloss_prevention_handler/build
    ulimit -n 10240 && just search_upload_handler/build
    ulimit -n 10240 && just document_text_extractor/build
    ulimit -n 10240 && just email_suppression_handler/build
    ulimit -n 10240 && just deleted_item_poller/build
    ulimit -n 10240 && just email_refresh_handler/build
    ulimit -n 10240 && just user_link_cleanup_handler/build
    ulimit -n 10240 && just email_scheduled_handler/build
    ulimit -n 10240 && just email_sfs_delete_handler/build

# TESTING

# Copies over necessary .env files for sqlx tests
setup_test_envs:
    echo "DATABASE_URL={{ MACRODB }}" >> ./contacts_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./notification_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./notification/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./properties_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./macro_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email_refresh_handler/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./comms_db_client/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./comms/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./document_cognition_service/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./document_text_extractor/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./organization_retention_handler/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./organization_retention_trigger/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./organization_retention_handler/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./sha_cleanup_worker/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./roles_and_permissions/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./teams/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./frecency/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./soup/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./system_properties/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./properties/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./name_search/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email_contact_search/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./email_scheduled_handler/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./saved_views/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./channels/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./comms_service/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./documents/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./stream/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./macro_project_utils/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./entity_access/.env
    echo "DATABASE_URL={{ MACRODB }}" >> ./github/.env

setup_macrodb:
    just macro_db_client/create_db
    just macro_db_client/migrate_db

initialize_dbs: setup_macrodb
