export DYNAMO_ENDPOINT_URL := 'http://localhost:8000'


set dotenv-load := true
set dotenv-required := false

mod ensure '../../tooling/just/ensure.just'
mod ci '../../tooling/just/ci.just'

deploy-dev:
    just ci::deploy-dev document-storage-service

run: ensure::ensure_dynamodb
    cargo run -F local

check:
    SQLX_OFFLINE=true cargo check
