lambda_name := file_name(justfile_directory())

build compiler="":
    cargo lambda build {{ if compiler == "" { "" } else { "--compiler " + compiler } }} --release --bin {{lambda_name}} --output-format zip
