name: Preview cloud storage pulumi stack
description: Run pulumi preview (dry run) for a pulumi stack from cloud-storage

inputs:
  use-docker:
    description: 'Whether to setup docker'
    required: false
    default: 'true'
  use-lfs:
    description: 'Whether to checkout LFS content'
    required: false
    default: 'false'
  environment:
    description: 'Environment to preview'
    required: false
    default: 'dev'
  aws-access-key:
    description: 'AWS access key'
    required: true
  aws-secret-key:
    description: 'AWS secret key'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  pulumi-access-token:
    description: 'The access token for pulumi'
    required: true
  pulumi-service-name:
    description: 'The name of the pulumi service to preview. This will be the exact name of the folder containing your stacks.'
    required: true
  dd-app-key:
    description: 'Datadog app key'
    required: true
  dd-api-key:
    description: 'Datadog api key'
    required: true
  dd-host:
    description: 'Datadog host'
    required: false
    default: 'https://api.us5.datadoghq.com/'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ''

runs:
  using: composite
  steps:
    # checkout the repo
    - uses: actions/checkout@v4
      with:
        lfs: ${{ inputs.use-lfs }}

    # setup docker
    - uses: docker/setup-buildx-action@v3
      if: ${{ inputs.use-docker == 'true' }}

    # install bun
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.0

    # install dependencies in infra folder
    - name: install infra dependencies
      shell: bash
      run: |
        cd infra 
        bun install

    # configure aws credentials
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}

    # login to ecr to allow pulumi to pull down services for caching
    - name: login to ecr
      shell: bash
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 569036502058.dkr.ecr.us-east-1.amazonaws.com

    # preview changes
    - uses: pulumi/actions@v5
      with:
        command: preview
        stack-name: macro-inc/${{ inputs.environment }}
        work-dir: ./infra/stacks/${{ inputs.pulumi-service-name }}
        comment-on-pr: ${{ inputs.github-token != '' }}
        github-token: ${{ inputs.github-token }}
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi-access-token }}
        DD_APP_KEY: ${{ inputs.dd-app-key }}
        DD_API_KEY: ${{ inputs.dd-api-key }}
        DD_HOST: ${{ inputs.dd-host }}
