-- Favorites: a user's personal ordered collection of entities.
CREATE TABLE favorite
(
    -- Ids are UUID v7, generated by the application on insert.
    id            UUID PRIMARY KEY NOT NULL,
    user_id       TEXT             NOT NULL REFERENCES "User" (id) ON DELETE CASCADE,
    entity_type   TEXT             NOT NULL,
    entity_id     TEXT             NOT NULL,
    sort_order    DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ      NOT NULL DEFAULT now()
);

-- One favorite per entity per user.
CREATE UNIQUE INDEX favorite_user_entity_uq
    ON favorite (user_id, entity_type, entity_id);

-- Ordered listing per user.
CREATE INDEX favorite_user_sort_idx ON favorite (user_id, sort_order);

-- Reverse lookup: "is this entity favorited?" checks by (entity_type, entity_id).
CREATE INDEX favorite_entity_idx ON favorite (entity_type, entity_id);
