lambda_name := file_name(justfile_directory())

import '../database.just'

test:
    cargo test --all-features

build compiler="":
    SQLX_OFFLINE=true cargo lambda build {{ if compiler == "" { "" } else { "--compiler " + compiler } }} --release --bin {{lambda_name}} --output-format zip

check:
  SQLX_OFFLINE=true cargo check

create-queues:
	AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name sfs-delete-queue.fifo

prepare_db:
	DATABASE_URL={{ DATABASE_URL }} sqlx prepare