import { Cursor } from '@macro-inc/automerge';
import type { SelectionCodec } from '@macro-inc/collaboration/collab/awareness';

/** A cursor for a node in an Automerge document */
export type NodeCursor = {
  /** the custom unique ID of the node
   * which is generated by the nodeId plugin
   * NOT the node's key */
  nodeId: string;
  /** the automerge representation of the cursor */
  cursor: Cursor;
};

/** Serialized NodeCursor */
type NodeCursorRaw = {
  nodeId: string;
  cursor: number[];
};

/** Conver a Lexical node cursor to a raw node cursor */
function toRaw(cursor: NodeCursor): NodeCursorRaw {
  return {
    nodeId: cursor.nodeId,
    cursor: Array.from(cursor.cursor.encode()),
  };
}

/** Conver a raw node cursor to a Lexical node cursor */
function fromRaw(raw: NodeCursorRaw): NodeCursor {
  return {
    nodeId: raw.nodeId,
    cursor: Cursor.decode(new Uint8Array(raw.cursor)),
  };
}

type LexicalSelectionAwarenessRaw = {
  anchor: NodeCursorRaw;
  focus: NodeCursorRaw;
};

export type LexicalSelectionAwareness = {
  anchor: NodeCursor;
  focus: NodeCursor;
};

export const lexicalSelectionCodec: SelectionCodec<
  LexicalSelectionAwareness,
  LexicalSelectionAwarenessRaw
> = {
  encode: (selection) => {
    return {
      anchor: toRaw(selection.anchor),
      focus: toRaw(selection.focus),
    };
  },
  decode: (serialized) => {
    return {
      anchor: fromRaw(serialized.anchor),
      focus: fromRaw(serialized.focus),
    };
  },
};
