[package]
name = "tauri-plugin-android-auth"
version = "0.1.0"
edition.workspace = true
links = "tauri-plugin-android-auth"

[build-dependencies]
tauri-plugin = { version = "2.4", features = ["build"] }

[dependencies]
serde = { workspace = true, features = ["derive"] }
tauri = { workspace = true }
