[package]
name = "cache-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
apollo-parser = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
lru = { workspace = true }
sha2 = { workspace = true }

[build-dependencies]
apollo-compiler = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
pollster = "0.4"
