config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  properties-service:macro_db_secret_key: macro-db-prod
  properties-service:fusionauth_client_id: 75409999-7dc4-4241-b73b-a51818c3a71c
  properties-service:fusionauth_issuer: auth.macro.com
  properties-service:internal_auth_key: document-storage-service-auth-key-prod
  properties-service:jwt_secret_key: fusionauth-jwt-secret-prod