lambda_name := file_name(justfile_directory())
DATABASE_URL := "postgres://user:password@localhost:5432/macrodb"

mod ci '../ci.just'
mod sqlx '../sqlx.just'

deploy-dev:
    just ci::deploy-dev organization-retention

prepare_db:
    just sqlx::prepare_db {{ DATABASE_URL }}

test:
    cargo test --all-features

build:
    SQLX_OFFLINE=true cargo lambda build --release --bin {{lambda_name}} --output-format zip