lambda_name := file_name(justfile_directory())

mod ci '../ci.just'

deploy-dev:
    just ci::deploy-dev organization-retention

test:
    cargo test --all-features

build compiler="":
    SQLX_OFFLINE=true cargo lambda build {{ if compiler == "" { "" } else { "--compiler " + compiler } }} --release --bin {{lambda_name}} --output-format zip