[package]
edition = "2024"
name = "cursor_api_key"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
aws-sdk-kms = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
zeroize = { workspace = true }

[dev-dependencies]
macro_db_migrator = { path = "../macro_db_migrator" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
