config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  connection-gateway:datadog_api_key:
    secure: AAABALynj0cHxXLf2IpP9eX0hWIIYfBBKlvnhszUc0Znr90NUNvLMJ8x/voedq/FlYoyLBdt5sYLFQfp99UDfA==
  connection-gateway:fusionauth_client_id: eb75fe7a-0ef1-4186-96d9-cc62cfb1d10c
  connection-gateway:fusionauth_issuer: fusionauth-dev.macro.com
  connection-gateway:internal_auth_key: document-storage-service-auth-key-dev
  connection-gateway:jwt_secret_key: fusionauth-jwt-secret-dev
  connection-gateway:legacy_jwt_secret_key: jwt-secret-dev
  connection-gateway:macro_db_secret_key: macro-db-dev
