set dotenv-load := true

mod ci '../ci.just'

deploy-dev:
    just ci::deploy-dev authentication-service

run:
    cargo run

check:
    SQLX_OFFLINE=true cargo check

generate_keys_dev:
    rm -rf ./output && mkdir output && cargo run --bin generate_keys dev

generate_keys_prod:
    rm -rf ./output && mkdir output && cargo run --bin generate_keys prod

create_localstack:
    docker run -d --name localstack -p 4566:4566 -e SERVICES=sqs localstack/localstack

start_localstack:
    docker run -p 4566:4566 -e SERVICES=sqs localstack/localstack

create_queue:
    AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name notification-queue

run-local:
    SQLX_OFFLINE=true cargo run --features macro_middleware/local_auth
