[package]
edition = "2024"
name = "notification_state"
publish = false
version = "0.1.0"

[features]
graphql = ["dep:async-graphql"]
postgres = ["dep:sqlx"]
schema = ["dep:schemars", "dep:utoipa"]

[dependencies]
async-graphql = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
sqlx = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
