[package]
edition = "2024"
name = "macro_event_broker"
publish = false
version = "0.1.0"

[features]
default = ["ports", "outbound"]
outbound = [
  "dep:aws-msk-iam-sasl-signer",
  "dep:aws-types",
  "dep:macro_env",
  "dep:macro_env_var",
  "dep:rdkafka",
  "ports",
]
ports = ["dep:tokio"]

[dependencies]
aws-msk-iam-sasl-signer = { workspace = true, optional = true }
aws-types = { workspace = true, optional = true }
macro_env = { path = "../macro_env", optional = true }
macro_env_var = { path = "../macro_env_var", optional = true }
rootcause = { workspace = true }
rdkafka = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"], optional = true }
tracing = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
macro_event_topics = { path = "../macro_event_topics" }

[dev-dependencies]
tokio = { workspace = true }
