[package]
edition = "2024"
name = "webhook"
publish = false
version = "0.1.0"

[features]
default = ["inbound", "outbound", "ports"]
inbound = [
  "dep:axum",
  "dep:axum-extra",
  "dep:model-error-response",
  "dep:model_user",
  "dep:rate_limit",
  "rate_limit/axum",
  "dep:serde_json",
  "dep:utoipa",
  "ports",
]
outbound = [
  "dep:hex",
  "dep:hmac",
  "dep:reqwest",
  "dep:sha2",
  "dep:sqlx",
  "dep:url",
  "ports",
]
ports = ["dep:serde_json"]

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, optional = true }
axum-extra = { workspace = true, optional = true }
chrono = { workspace = true }
hex = { workspace = true, optional = true }
hmac = { workspace = true, optional = true }
macro_user_id = { path = "../macro_user_id" }
model-error-response = { path = "../model-error-response", optional = true }
model_user = { path = "../model_user", optional = true, features = ["axum"] }
rate_limit = { path = "../rate_limit", optional = true, default-features = false }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
rate_limit = { path = "../rate_limit", default-features = false, features = [
  "axum",
  "testing",
] }
