lambda_name := file_name(justfile_directory())

mod ci '../ci.just'

deploy-dev:
    just ci::deploy-dev deleted-item-poller

test:
    cargo test --all-features

build:
    SQLX_OFFLINE=true cargo lambda build --release --bin {{lambda_name}} --output-format zip

check:
  SQLX_OFFLINE=true cargo check
