mod ci '../../tooling/just/ci.just'

deploy-dev:
	just ci::deploy-dev convert-service

check:
	SQLX_OFFLINE=true cargo check

create-localstack:
	docker run -d --name localstack -p 4566:4566 -e SERVICES=sqs macro-local-localstack:dev

start-localstack:
	docker run -p 4566:4566 -e SERVICES=sqs macro-local-localstack:dev

create-queue:
	AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name convert-queue
