lambda_name := file_name(justfile_directory())

test:
    cargo test --all-features

build compiler="":
	SQLX_OFFLINE=true cargo lambda build {{ if compiler == "" { "" } else { "--compiler " + compiler } }} --release --bin {{lambda_name}} --output-format zip

create-localstack:
	docker run -d --name localstack -p 4566:4566 -e SERVICES=sqs macro-local-localstack:dev

start-localstack:
	docker run -p 4566:4566 -e SERVICES=sqs macro-local-localstack:dev

create-queue:
	AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name my-test-queue
