[package]
name = "graphql_channel"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-graphql = { workspace = true }
channels = { path = "../channels", default-features = false, features = ["ports"] }
entity_access = { path = "../entity_access", default-features = false, features = ["ports"] }
graphql_common = { path = "../graphql_common" }
macro_user_id = { path = "../macro_user_id" }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
chrono = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
