set dotenv-load := true

mod ci '../ci.just'

deploy-dev:
    just ci::deploy-dev contacts-service

test-post:
    curl -X POST \
         -H "Content-Type: application/json" \
         -d @tests/fixtures/add_connection.json \
         http://127.0.0.1:3030/messages

sqs-test-message:
    AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs send-message \
      --queue-url http://localhost:4566/000000000000/my-test-queue \
      --message-body file://tests/fixtures/add_connection.json

send-message JSON_FILE:
    AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs send-message \
      --queue-url http://localhost:4566/000000000000/my-test-queue \
      --message-body file://{{ JSON_FILE }}

sqs-test-bad-message:
    aws --endpoint-url=http://localhost:4566 sqs send-message \
      --queue-url http://localhost:4566/000000000000/my-test-queue \
      --message-body "lol this isn't a real messge" 

purge-queue:
    AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs purge-queue --queue-url http://localhost:4566/000000000000/my-test-queue

create-localstack:
    docker run -d --name localstack -p 4566:4566 -e SERVICES=sqs localstack/localstack

start-localstack:
    docker run -p 4566:4566 -e SERVICES=sqs localstack/localstack

create-queue:
    AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name my-test-queue

sqs-worker:
    cargo run --example worker | jq

# runs contacts query when JWT middlewhere is running.
# expects a file called "access_token". This can be made by
# copying the dev-macro-access-token cookie and pasting it into

# access token
contacts:
    curl -X 'GET' \
      -H "Authorization: Bearer $(cat access_token)" \
      'http://localhost:8080/contacts'

test:
    SQLX_OFFLINE=true cargo test

run:
    cargo run --features mock

check:
    SQLX_OFFLINE=true cargo check

list-connections:
    echo "SELECT * FROM connections" | PGPASSWORD=password  psql -h localhost -U user contacts

test-integration:
    cargo test -- --ignored test_integration
