//! Image requests, generated bytes, and provider errors.

use entity_access::domain::models::{EditAccessLevel, EntityAccessReceipt};
use model::document::FileType;

/// The shape of image the model is asked for, as the model vocabulary calls
/// it. The closed set keeps the agent from inventing ratios the provider
/// rejects.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageAspectRatio {
    /// 1:1
    Square,
    /// 4:3
    Landscape,
    /// 3:4
    Portrait,
    /// 16:9
    Widescreen,
    /// 9:16
    Tall,
}

impl ImageAspectRatio {
    /// The `width:height` form image providers accept.
    pub fn as_ratio(self) -> &'static str {
        match self {
            Self::Square => "1:1",
            Self::Landscape => "4:3",
            Self::Portrait => "3:4",
            Self::Widescreen => "16:9",
            Self::Tall => "9:16",
        }
    }
}

/// What to generate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageGenerationRequest {
    /// Natural-language description of the image.
    pub prompt: String,
    /// Requested shape; the provider default when `None`.
    pub aspect_ratio: Option<ImageAspectRatio>,
    /// Reference photos in the order the prompt refers to them.
    pub reference_images: Vec<ReferenceImage>,
}

/// A saved image the caller wants to use as a reference.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageReference {
    /// A Macro document, read with the caller's document permissions.
    Document(uuid::Uuid),
    /// An uploaded static file, identified by its public capability ID.
    StaticFile(uuid::Uuid),
}

/// Image bytes resolved internally for the provider, never returned in tool output.
#[derive(Clone, PartialEq, Eq)]
pub struct ReferenceImage {
    /// Encoded image bytes.
    pub bytes: Vec<u8>,
    /// Media type of the encoded bytes.
    pub mime_type: String,
}

impl std::fmt::Debug for ReferenceImage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ReferenceImage")
            .field("size_bytes", &self.bytes.len())
            .field("mime_type", &self.mime_type)
            .finish()
    }
}

/// Why a reference photo could not be loaded.
#[derive(Debug, thiserror::Error)]
pub enum ReadImageError {
    /// This host has no reference reader configured.
    #[error("reference images are not available on this host")]
    Unavailable,
    /// The caller cannot read the requested source.
    #[error("reference image is missing or you do not have access to it")]
    Unauthorized,
    /// The reference does not resolve to one image.
    #[error("reference must identify an image file")]
    NotImage,
    /// Storage or image decoding failed.
    #[error("could not read the reference image: {0}")]
    Internal(rootcause::Report),
}

/// A generated image, as the provider returned it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedImage {
    /// Encoded image bytes in the format `mime_type` names.
    pub bytes: Vec<u8>,
    /// IANA media type of `bytes`, e.g. `image/png`.
    pub mime_type: String,
    /// Any commentary the model produced alongside the image.
    pub note: Option<String>,
}

impl GeneratedImage {
    /// The Macro file type for `mime_type`; `None` for a media type Macro
    /// does not know as an image.
    pub fn file_type(&self) -> Option<FileType> {
        match self.mime_type.as_str() {
            "image/png" => Some(FileType::Png),
            "image/jpeg" | "image/jpg" => Some(FileType::Jpg),
            "image/webp" => Some(FileType::Webp),
            "image/gif" => Some(FileType::Gif),
            _ => None,
        }
    }
}

/// Why an image could not be generated.
#[derive(Debug, thiserror::Error)]
pub enum ImageGenerationError {
    /// No provider is configured in this host.
    #[error("image generation is not configured")]
    Unavailable,
    /// The provider declined to render this prompt (safety filters, or the
    /// model answered in text instead of an image). The message is written
    /// for the agent that asked.
    #[error("{0}")]
    Refused(String),
    /// The provider call failed: transport, authentication, quota, or an
    /// unparseable response.
    #[error("image provider request failed")]
    Provider(#[source] anyhow::Error),
}

/// Longest prompt forwarded to the provider, in bytes.
pub const MAX_PROMPT_BYTES: usize = 8 * 1024;

/// Product limit matching the image model's recommended reference count.
pub const MAX_REFERENCE_IMAGES: usize = 3;

/// Total encoded image bytes before Base64 expansion, below the provider's 20 MB request limit.
pub const MAX_REFERENCE_BYTES: usize = 12 * 1024 * 1024;

/// An image to generate and store as a document.
pub struct NewGeneratedImage {
    /// Natural-language description of the image.
    pub prompt: String,
    /// Requested shape; the provider default when `None`.
    pub aspect_ratio: Option<ImageAspectRatio>,
    /// Document name; the extension is added from the generated format. A
    /// name that already carries an image extension keeps it. `None` names
    /// the document after the opening words of the prompt.
    pub file_name: Option<String>,
    /// Edit capability for the destination project, minted for the creating
    /// principal; absent for top-level files.
    pub project: Option<EntityAccessReceipt<EditAccessLevel>>,
    /// Reference images, resolved under the creating principal before generation.
    pub reference_images: Vec<ImageReference>,
}

/// A generated image stored as a document.
#[derive(Debug)]
pub struct GeneratedImageDocument {
    /// The created document.
    pub document_id: uuid::Uuid,
    /// Final filename, including its extension.
    pub file_name: String,
    /// IANA media type of the stored bytes.
    pub mime_type: String,
    /// Number of stored bytes.
    pub size_bytes: usize,
    /// Any commentary the model produced alongside the image.
    pub note: Option<String>,
}

/// Why a generated image document was not created.
#[derive(Debug, thiserror::Error)]
pub enum GenerateImageError {
    /// The prompt is invalid.
    #[error("{0}")]
    BadRequest(String),
    /// A requested reference image could not be loaded.
    #[error(transparent)]
    Reference(#[from] ReadImageError),
    /// The image could not be generated.
    #[error(transparent)]
    Generation(#[from] ImageGenerationError),
    /// The image was generated but not stored.
    #[error(transparent)]
    Document(#[from] SaveImageError),
}

/// Generated bytes and metadata to persist as a Macro document.
pub struct NewImageDocument {
    /// Filename including the image extension.
    pub file_name: String,
    /// Encoded image bytes.
    pub bytes: Vec<u8>,
    /// Verified edit capability for the destination project.
    pub project: Option<EntityAccessReceipt<EditAccessLevel>>,
}

/// Failure returned by the document-saving capability.
#[derive(Debug, thiserror::Error)]
pub enum SaveImageError {
    /// Invalid filename or file bytes.
    #[error("{0}")]
    BadRequest(String),
    /// The document name exceeds its allowed length.
    #[error("fileName is too long (maximum {max} characters)")]
    NameTooLong {
        /// Maximum permitted name length.
        max: usize,
    },
    /// The supplied destination capability does not authorize this principal.
    #[error("unauthorized destination project")]
    Unauthorized,
    /// Document persistence failed.
    #[error("could not save the generated image: {0}")]
    Internal(rootcause::Report),
}
