# Convert sops encrypted env file to .env file
get_environment:
  sops --input-type dotenv --output-type dotenv -d .env-local.enc > .env

# Edit the sops file
edit_environment:
  sops --input-type dotenv --output-type dotenv .env-local.enc
