export DYNAMO_ENDPOINT_URL := 'http://localhost:8000'


set dotenv-load := true
set dotenv-required := false

mod ensure '../ensure.just'
mod ci '../ci.just'

deploy-dev:
    just ci::deploy-dev document-storage

run: ensure::ensure_dynamodb
    cargo run -F local

check:
    SQLX_OFFLINE=true cargo check
