name: Setup Prereqs Web
description: Checkout and Setup Prerequisite Dependencies for web app
inputs:
  playwright:
    description: Install Playwright and cache
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      shell: bash
      working-directory: js/app
      run: |
        bun install --frozen-lockfile
        bun add -g npm

    - name: Get week number (for caching Playwright)
      if: inputs.playwright == 'true'
      shell: bash
      run: echo "CACHE_WEEK=$(date +%Y-%V)" >> $GITHUB_ENV
    - name: Restore Playwright browsers
      if: inputs.playwright == 'true'
      id: pw-browsers
      uses: runs-on/cache/restore@v4
      with:
        path: js/app/node_modules/playwright-core/.local-browsers
        key: pw-browsers-${{ env.CACHE_WEEK }}
        restore-keys: pw-browsers-
    - name: Install Playwright Browsers
      if: inputs.playwright == 'force' || (inputs.playwright == 'true' && steps.pw-browsers.outputs.cache-hit != 'true')
      shell: bash
      working-directory: js/app
      run: PLAYWRIGHT_BROWSERS_PATH=0 bunx playwright install chromium
    - name: Save Playwright browsers to cache
      if: inputs.playwright == 'force' || (inputs.playwright == 'true' && steps.pw-browsers.outputs.cache-hit != 'true')
      uses: runs-on/cache/save@v4
      with:
        path: js/app/node_modules/playwright-core/.local-browsers
        key: pw-browsers-${{ hashFiles('js/app/bun.lock')}}
