[package]
name = "graphql_common"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-graphql = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
filter_ast = { path = "../filter_ast" }
item_filters = { path = "../item_filters" }
macro_authorization = { path = "../macro_authorization", default-features = false, features = ["axum"] }
macro_user_id = { path = "../macro_user_id" }
model-entity = { path = "../model-entity" }
models_properties = { path = "../models_properties" }
tokio = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
model_user = { path = "../model_user" }
rootcause = { workspace = true }
