[package]
edition = "2024"
name = "macro_middleware"
publish = false
version = "0.1.0"

[features]
all = ["auth", "cloud_storage", "tracking"]
auth = []
cloud_storage = [
  "dep:entity_access_db_utils",
  "dep:macro_user_id",
  "macro_db_client",
]
default = ["all"]
macro_db_client = ["dep:macro_db_client", "dep:sqlx"]
tracking = ["dep:ip_extractor"]

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
entity_access_db_utils = { path = "../entity_access_db_utils", optional = true }
ip_extractor = { path = "../ip_extractor", optional = true }
macro_db_client = { path = "../macro_db_client", optional = true }
macro_env_var = { path = "../macro_env_var" }
macro_user_id = { path = "../macro_user_id", optional = true }
macro_uuid = { path = "../macro_uuid" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
models_permissions = { path = "../models_permissions" }
serde = { workspace = true }
sqlx = { workspace = true, optional = true }
tokio = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
