[package]
edition = "2024"
name = "email_refresh_handler"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
aws-sdk-sqs = { workspace = true }
macro_aws_config = { path = "../../crates/macro_aws_config" }
aws_lambda_events = { workspace = true, features = ["eventbridge"] }
chrono = { workspace = true }
lambda_runtime = { workspace = true }
macro_entrypoint = { path = "../../crates/macro_entrypoint" }
macro_env = { path = "../../crates/macro_env" }
macro_env_var = { path = "../../crates/macro_env_var" }
macro_queues = { path = "../../crates/macro_queues" }
model = { path = "../../crates/model" }
models_email = { path = "../../crates/models_email" }
sqlx = { workspace = true }
sqs_client = { path = "../../crates/sqs_client" }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

[package.metadata.cargo-machete]
ignored = []

[dev-dependencies]
macro_db_migrator = { path = "../../crates/macro_db_migrator" }
