package com.macro.preprocess.parse;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public final class AnomalyWordLists {

	private AnomalyWordLists() {
	}

	public static final String[] brokenSectionReferenceIgnoreList = {
		"of",
		"in"
	};

  // Phrases indicating that an identified "definition" is a reference to a full definition elsewhere in the document.
  public static final String[] duplicateDefIndicator = {
    "the meaning set forth", 
    "the meaning set out",
    "the meaning specified",
    "the meaning assigned to such term",
    "described in",
    "as defined",
    "in this section"
  };

	 // List of terms which if included in an undefined term error should not be reported.
	static final String[] undefinedTermIndicator = {
		// References to laws or other documentation
		"act",
		"agreement",
		"amendment",
		"appendix",
		"article",
		"chapter",
		"code",
		"decree",
		"exhibit",
		"form",
		"law",
		"no.",
		"part",
		"regulation",
		"schedule",
		"title",
		// Entities likely to be proper nouns
		"agency",
		"association",
		"avenue",
		"bank",
		"commission",
		"communications",
		"corp",
		"corporation",
		"county",
		"court",
		"district",
		"enterprise",
		"fund",
		"holdings",
		"inc.",
		"incorporated",
		"institute",
		"islands",
		"llc",
		"llp",
		"new york",
		"north america",
		"office",
		"program",
		"rapids",
		"river",
		"road",
		"services",
		"solutions",
		"street",
		"system",
		"technologies",
		"telephone company",
		"town",
		"treasury",
		"trust company",
		"union",
    "united states",
		"valley",
		// Miscellaneous common terms
		"chief executive officer",
		"chief financial officer",
		"defined terms",
		"her majesty",
		"other conditions",
		"etc",
		":",
		"boulevard",
		"bylaws",
		"circular",
		"city",
		"clause",
		"commonwealth",
		"confederation",
		"constitution",
		"cooperative",
		"directive",
		"division",
		"european union",
		"executive order",
		"foundation",
		"guideline",
		"hospital",
		"initiative",
		"judgment",
		"limited",
		"ltd",
		"memorandum",
		"municipality",
		"order",
		"partnership",
		"patent",
		"policy",
		"precedent",
		"province",
		"public limited company",
		"plc",
		"resolution",
		"rule",
		"section",
		"securities",
		"statute",
		"subdivision",
		"subsection",
		"territory",
		"treaty",
		"united nations",
		"united kingdom",
		"university",
		"vice president",
		"village",
		"world trade organization",
		"wto",
		"zone",
		// Miscellaneous common terms
		"attorney general",
		"department of justice",
		"federal trade commission",
		"internal revenue service",
		"minister",
		"secretary",
		"supreme court",
		"world health organization",
		"who",
		"world bank",
		"international monetary fund",
		"imf",
		"north atlantic treaty organization",
		"nato",
		"government",
		"state",
		"tribunal",
		"panel",
		"international court of justice",
		// countries
		"australia",
		"austria",
		"bahrain",
		"belgium",
		"brazil",
		"canada",
		"china",
		"cyprus",
		"czech republic",
		"denmark",
		"egypt",
		"finland",
		"france",
		"germany",
		"gibraltar",
		"greece",
		"hong kong",
		"hungary",
		"india",
		"indonesia",
		"ireland",
		"israel",
		"italy",
		"japan",
		"jersey",
		"kuwait",
		"luxembourg",
		"malaysia",
		"malta",
		"mexico",
		"monaco",
		"netherlands",
		"new zealand",
		"norway",
		"oman",
		"panama",
		"philippines",
		"poland",
		"portugal",
		"qatar",
		"republic of korea",
		"russia",
		"saudi arabia",
		"singapore",
		"slovakia",
		"slovenia",
		"south africa",
		"spain",
		"sweden",
		"switzerland",
		"taiwan",
		"thailand",
		"turkey",
		"united arab emirates",
		"uae",
		"ukraine",
		"united kingdom",
		"great britain",
		"uk",
		"usa",
		"u.s",
		"u.s.a",
		"united states",
		"vatican city",
		"venezuela",
		"vietnam",
		"blvd.",
		"st.",
		"rd.",
		"mr.",
		"ms.",
		"mrs.",
		"dr.",
		"jr.",
		"the ",
		"company",
		"north",
		"south",
		"east",
		"west",
	};

  // Indicators that the text referencing a "missing section" is referencing an external law/etc.
  static final String[] msArr = {"act", "code", "u.c.c", "ucc", "united states"};
  public static final Set<String> missingSectionIndicator = new HashSet<String>(Arrays.asList(msArr));

  // Punctuation after which a capitalized letter is anticipated.
  static final String[] punctArr = {".","?","!", ":", " "};
  public static final Set<String> punctuationSet = new HashSet<String>(Arrays.asList(punctArr));
}
