[package]
edition = "2024"
name = "search_upload_handler"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
aws_lambda_events = { workspace = true, features = ["eventbridge"] }
document_storage_service_client = { path = "../../crates/document_storage_service_client" }
lambda_runtime = { workspace = true }
macro_entrypoint = { path = "../../crates/macro_entrypoint" }
macro_env_var = { path = "../../crates/macro_env_var" }
macro_service_urls = { path = "../../crates/macro_service_urls" }
s3_key = { path = "../../crates/s3_key" }
tokio = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }
