config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  email-service:authentication_service_internal_api_key: authentication-service-internal-api-key-prod
  email-service:jwt_secret_key: fusionauth-jwt-secret-prod
  email-service:fusionauth_client_id: fusionauth-client-id-key-prod
  email-service:fusionauth_issuer: auth.macro.com
  email-service:db_password_secret_key: email-db-password-prod
  email-service:internal_auth_key: document-storage-service-auth-key-prod
  email-service:cf_private_key: email-attachments-private-key-prod
  email-service:notifications_enabled: true
  email-service:use_apollo_crm_enrichment: false
  email-service:apollo_api_key_secret_name: apollo-io-api-key-master
  email-service:sent_undo_delay_secs: 5
  email-service:redis_rate_limit_reqs: 14000
  email-service:redis_rate_limit_reqs_backfill: 13000
  email-service:redis_rate_limit_window_secs: 60
  email-service:backfill_queue_workers: 25
  email-service:backfill_queue_max_messages: 1
  email-service:inbox_sync_queue_workers: 25
  email-service:inbox_sync_queue_max_messages: 1
  email-service:inbox_sync_retry_queue_workers: 5
  email-service:inbox_sync_retry_queue_max_messages: 1
  email-service:gmail_ops_queue_workers: 25
  email-service:gmail_ops_queue_max_messages: 1
  email-service:gmail_ops_retry_queue_workers: 5
  email-service:gmail_ops_retry_queue_max_messages: 1
  email-service:sfs_uploader_workers: 3
  email-service:presigned_url_ttl_secs: 3600
  email-service:gmail_gcp_queue: gmail-gcp-queue-prod
  email-service:macro_db_secret_key: macro-db-prod
  email-service:delete_unused_after_days: 7
  email-service:delete_inactive_after_days: 60
  email-service:inbox_health_poll_interval_hours: 6
