set dotenv-load := true

mod ci '../ci.just'

deploy-dev:
    just ci::deploy-dev comms-service

run:
    cargo run

build:
    SQLX_OFFLINE=true cargo build

check:
    SQLX_OFFLINE=true cargo check

clippy:
    SQLX_OFFLINE=true cargo clippy

run-local:
    cargo run --features macro_middleware/local_auth
