DATABASE_URL := "postgres://user:password@localhost:5432/macrodb"

mod sqlx '../sqlx.just'

prepare_db:
    just sqlx::prepare_db {{ DATABASE_URL }}

test $DATABASE_URL=DATABASE_URL:
    cargo test

psql $DATABASE_URL=DATABASE_URL:
    PGPASSWORD=password psql -h localhost -U user macrodb
