DATABASE_URL := "postgres://user:password@localhost:5432/macrodb"

mod sqlx '../sqlx.just'

prepare_db:
    just sqlx::prepare_db {{ DATABASE_URL }}

export RUSTFLAGS := "-Dwarnings"
export RUSTDOCFLAGS := "-Dwarnings"
export CARGO_TERM_COLOR := "always"

clippy:
  cargo clippy

clippy-fix:
  cargo clippy --fix

fmt-check:
  cargo fmt --check

fmt:
  cargo fmt

check:
  cargo check

test:
  cargo test
