// This file has been generated by Specta. Do not edit this file manually.
/**
 *  One complete ACP JSON-RPC message routed between the Agent Service and the
 *  single agent execution hosted by this connection.
 *
 *  Its own JSON-RPC fields are opaque to TypeScript consumers here (typed as
 *  an arbitrary object of unknown values): they already have a proper ACP SDK
 *  on the TypeScript side, so this crate only needs to guarantee the message
 *  round-trips unchanged. This is typed as a map rather than plain `unknown`
 *  because [`ToRuntimeMessage`]/[`ToServerMessage`] carry it in an internally
 *  tagged `Acp` variant, which requires its payload provably serialize as an
 *  object so the `"type"` tag can be merged into it. `#[serde(transparent)]`
 *  changes nothing about the actual wire format here - a single-field tuple
 *  struct already serializes transparently by default - but it does tell
 *  specta's serde-compatibility checker that this newtype is transparent, so
 *  it looks through to the map type below instead of treating `AcpMessage`
 *  itself as an opaque, non-mergeable struct.
 */
export type AcpMessage = { [key in string]: unknown };

/**  Agent Service to Agent Runtime traffic on the logical protocol stream. */
export type ToRuntimeMessage =
/**  An ACP message routed to the hosted agent. */
{
	type: "acp",
} & AcpMessage;

/**  Agent Runtime to Agent Service traffic on the logical protocol stream. */
export type ToServerMessage =
/**  An ACP message routed from the hosted agent. */
{
	type: "acp",
} & AcpMessage |
/**  A runtime or agent lifecycle event. */
{ type: "event";
/**  The event name. */
event: string };
