// This file has been generated by Specta. Do not edit this file manually.
/**
 *  One complete ACP JSON-RPC message routed between the Agent Service and the
 *  single agent execution hosted by this connection.
 *
 *  Its own JSON-RPC fields are opaque to TypeScript consumers here (typed as
 *  an arbitrary object of unknown values): they already have a proper ACP SDK
 *  on the TypeScript side, so this crate only needs to guarantee the message
 *  round-trips unchanged. This is typed as a map rather than plain `unknown`
 *  because [`ToRuntimeMessage`]/[`ToServerMessage`] carry it in an internally
 *  tagged `Acp` variant, which requires its payload provably serialize as an
 *  object so the `"type"` tag can be merged into it. `#[serde(transparent)]`
 *  changes nothing about the actual wire format here - a single-field tuple
 *  struct already serializes transparently by default - but it does tell
 *  specta's serde-compatibility checker that this newtype is transparent, so
 *  it looks through to the map type below instead of treating `AcpMessage`
 *  itself as an opaque, non-mergeable struct.
 */
export type AcpMessage = { [key in string]: unknown };

/**  The result of probing a fresh ACP subprocess. */
export type ModelProbeResult =
/**  The raw options returned by `session/new`. */
{ status: "available";
/**  Session configuration options exactly as the agent returned them. */
configOptions: unknown[] } |
/**  A safe, operator-actionable failure description. */
{ status: "error";
/**  Failure text safe to return across the runtime connection. */
message: string };

/**  Versioned runtime capture outcome. The owning review domain validates snapshots. */
export type ReviewCaptureResult =
/**  Pinned diffd structural capture data. */
{ status: "available";
/**  Review capture schema, version one. */
capture: unknown } |
/**  The workspace cannot be captured by this runtime. */
{ status: "error";
/**  Safe error suitable for the reader and agent. */
message: string };

/**  Agent Service to Agent Runtime traffic on the logical protocol stream. */
export type ToRuntimeMessage =
/**  An ACP message routed to the hosted agent. */
{
	type: "acp",
} & AcpMessage |
/**
 *  Probe a separate fresh agent process for its session configuration.
 *
 *  The request carries no parameters: it asks this connection's one
 *  configured harness what it advertises. Answers are therefore
 *  interchangeable, so nothing correlates a response to a request.
 */
({ type: "modelProbeRequest" }) & { base?: never; head?: never; request_id?: never; workspace?: never } |
/**  Capture a session workspace outside the ACP conversation stream. */
{ type: "reviewCapture";
/**  Correlation ID, scoped to this live connection. */
request_id: string;
/**  Persisted session workspace, supplied only by the service. */
workspace: string;
/**  Base branch or pinned commit. */
base: string | null;
/**  Optional tip commit; absent means the working tree. */
head: string | null };

/**  Agent Runtime to Agent Service traffic on the logical protocol stream. */
export type ToServerMessage =
/**  An ACP message routed from the hosted agent. */
{
	type: "acp",
} & AcpMessage |
/**  A runtime or agent lifecycle event. */
({ type: "event";
/**  The event name. */
event: string }) & { chunk?: never; done?: never; request_id?: never; result?: never } |
/**  An answer to a connection-level model probe. */
({ type: "modelProbeResponse";
/**  Raw options or a safe failure. */
result: ModelProbeResult }) & { chunk?: never; done?: never; event?: never; request_id?: never } |
/**  One bounded UTF-8 chunk of a review capture, interleaved with ACP traffic. */
({ type: "reviewCaptureChunk";
/**  ID of the request this belongs to. */
request_id: string;
/**  Serialized capture data, at most 256 KiB before envelope escaping. */
chunk: string;
/**  This chunk completes the capture. */
done: boolean }) & { event?: never; result?: never } |
/**  An independently correlated review response; never logged as ACP traffic. */
({ type: "reviewCaptured";
/**  ID of the request this answers. */
request_id: string;
/**  Full structural snapshot or an actionable capability error. */
result: ReviewCaptureResult }) & { chunk?: never; done?: never; event?: never };
