[package]
name = "graphql_permission"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-graphql = { workspace = true, features = ["dataloader"] }
entity_access = { path = "../entity_access", default-features = false, features = [
  "ports",
] }
futures = { workspace = true }
macro_user_id = { path = "../macro_user_id" }
model-entity = { path = "../model-entity" }
rootcause = { workspace = true }
tokio = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
