-- The sequence is allocated after the mailbox acceptance lock, so concurrent
-- requests follow accepted intent order rather than transaction start time.
ALTER TABLE email_mailbox_commands ADD COLUMN accepted_order BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH ordered AS (SELECT id,row_number() OVER (ORDER BY created_at,id) AS ordinal FROM email_mailbox_commands)
UPDATE email_mailbox_commands c SET accepted_order=ordered.ordinal FROM ordered WHERE ordered.id=c.id;
SELECT setval(pg_get_serial_sequence('email_mailbox_commands','accepted_order'),COALESCE(max(accepted_order),1),count(*)>0) FROM email_mailbox_commands;
ALTER TABLE email_mailbox_commands ALTER COLUMN accepted_order SET GENERATED ALWAYS;
CREATE UNIQUE INDEX email_mailbox_commands_accepted_order ON email_mailbox_commands(accepted_order);
