config:
  aws:region: us-east-2
  observability:alarmTopicArn: arn:aws:sns:us-east-2:569036502058:observability-prod-alerts
  observability:amiId: ami-082c5befa76bfc246
  observability:secretArn: arn:aws:secretsmanager:us-east-2:569036502058:secret:observability/prod-TwQpBJ
