// TODO: auto-generate this file
// copied from macro-api generated type
// see: macro-api/cloud-storage/model/src/bin/generate_typescript_types.rs

export const FileTypeMap = {
  Docx: {
    extension: 'docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    app: 'write',
  },
  Pdf: { extension: 'pdf', mime: 'application/pdf', app: 'pdf' },
  Md: { extension: 'md', mime: 'text/markdown', app: 'md' },
  Canvas: {
    extension: 'canvas',
    mime: 'application/x-macro-canvas',
    app: 'canvas',
  },
  Coffee: { extension: 'coffee', mime: 'text/plain', app: 'code' },
  Cson: { extension: 'cson', mime: 'text/plain', app: 'code' },
  Iced: { extension: 'iced', mime: 'text/plain', app: 'code' },
  C: { extension: 'c', mime: 'text/plain', app: 'code' },
  I: { extension: 'i', mime: 'text/plain', app: 'code' },
  Cpp: { extension: 'cpp', mime: 'text/plain', app: 'code' },
  Cppm: { extension: 'cppm', mime: 'text/plain', app: 'code' },
  Cc: { extension: 'cc', mime: 'text/plain', app: 'code' },
  Ccm: { extension: 'ccm', mime: 'text/plain', app: 'code' },
  Cxx: { extension: 'cxx', mime: 'text/plain', app: 'code' },
  Cxxm: { extension: 'cxxm', mime: 'text/plain', app: 'code' },
  CPlusPlus: { extension: 'c++', mime: 'text/plain', app: 'code' },
  CPlusPlusm: { extension: 'c++m', mime: 'text/plain', app: 'code' },
  Hpp: { extension: 'hpp', mime: 'text/plain', app: 'code' },
  Hh: { extension: 'hh', mime: 'text/plain', app: 'code' },
  Hxx: { extension: 'hxx', mime: 'text/plain', app: 'code' },
  HPlusPlus: { extension: 'h++', mime: 'text/plain', app: 'code' },
  H: { extension: 'h', mime: 'text/plain', app: 'code' },
  Ii: { extension: 'ii', mime: 'text/plain', app: 'code' },
  Ino: { extension: 'ino', mime: 'text/plain', app: 'code' },
  Inl: { extension: 'inl', mime: 'text/plain', app: 'code' },
  Ipp: { extension: 'ipp', mime: 'text/plain', app: 'code' },
  Ixx: { extension: 'ixx', mime: 'text/plain', app: 'code' },
  Tpp: { extension: 'tpp', mime: 'text/plain', app: 'code' },
  Txx: { extension: 'txx', mime: 'text/plain', app: 'code' },
  HppIn: { extension: 'hpp.in', mime: 'text/plain', app: 'code' },
  HIn: { extension: 'h.in', mime: 'text/plain', app: 'code' },
  Cu: { extension: 'cu', mime: 'text/plain', app: 'code' },
  Cuh: { extension: 'cuh', mime: 'text/plain', app: 'code' },
  Cs: { extension: 'cs', mime: 'text/plain', app: 'code' },
  Csx: { extension: 'csx', mime: 'text/plain', app: 'code' },
  Cake: { extension: 'cake', mime: 'text/plain', app: 'code' },
  Css: { extension: 'css', mime: 'text/plain', app: 'code' },
  Dart: { extension: 'dart', mime: 'text/plain', app: 'code' },
  Diff: { extension: 'diff', mime: 'text/plain', app: 'code' },
  Patch: { extension: 'patch', mime: 'text/plain', app: 'code' },
  Rej: { extension: 'rej', mime: 'text/plain', app: 'code' },
  Dockerfile: { extension: 'dockerfile', mime: 'text/plain', app: 'code' },
  Containerfile: {
    extension: 'containerfile',
    mime: 'text/plain',
    app: 'code',
  },
  Go: { extension: 'go', mime: 'text/plain', app: 'code' },
  Handlebars: { extension: 'handlebars', mime: 'text/plain', app: 'code' },
  Hbs: { extension: 'hbs', mime: 'text/plain', app: 'code' },
  Hjs: { extension: 'hjs', mime: 'text/plain', app: 'code' },
  Hlsl: { extension: 'hlsl', mime: 'text/plain', app: 'code' },
  Hlsli: { extension: 'hlsli', mime: 'text/plain', app: 'code' },
  Fx: { extension: 'fx', mime: 'text/plain', app: 'code' },
  Fxh: { extension: 'fxh', mime: 'text/plain', app: 'code' },
  Vsh: { extension: 'vsh', mime: 'text/plain', app: 'code' },
  Psh: { extension: 'psh', mime: 'text/plain', app: 'code' },
  Cginc: { extension: 'cginc', mime: 'text/plain', app: 'code' },
  Compute: { extension: 'compute', mime: 'text/plain', app: 'code' },
  Html: { extension: 'html', mime: 'text/plain', app: 'code' },
  Htm: { extension: 'htm', mime: 'text/plain', app: 'code' },
  Shtml: { extension: 'shtml', mime: 'text/plain', app: 'code' },
  Xhtml: { extension: 'xhtml', mime: 'text/plain', app: 'code' },
  Xht: { extension: 'xht', mime: 'text/plain', app: 'code' },
  Mdoc: { extension: 'mdoc', mime: 'text/plain', app: 'code' },
  Jsp: { extension: 'jsp', mime: 'text/plain', app: 'code' },
  Asp: { extension: 'asp', mime: 'text/plain', app: 'code' },
  Aspx: { extension: 'aspx', mime: 'text/plain', app: 'code' },
  Jshtm: { extension: 'jshtm', mime: 'text/plain', app: 'code' },
  Volt: { extension: 'volt', mime: 'text/plain', app: 'code' },
  Ejs: { extension: 'ejs', mime: 'text/plain', app: 'code' },
  Rhtml: { extension: 'rhtml', mime: 'text/plain', app: 'code' },
  Ini: { extension: 'ini', mime: 'text/plain', app: 'code' },
  Conf: { extension: 'conf', mime: 'text/plain', app: 'code' },
  Properties: { extension: 'properties', mime: 'text/plain', app: 'code' },
  Cfg: { extension: 'cfg', mime: 'text/plain', app: 'code' },
  Directory: { extension: 'directory', mime: 'text/plain', app: 'code' },
  Gitattributes: {
    extension: 'gitattributes',
    mime: 'text/plain',
    app: 'code',
  },
  Gitconfig: { extension: 'gitconfig', mime: 'text/plain', app: 'code' },
  Gitmodules: { extension: 'gitmodules', mime: 'text/plain', app: 'code' },
  Editorconfig: { extension: 'editorconfig', mime: 'text/plain', app: 'code' },
  Repo: { extension: 'repo', mime: 'text/plain', app: 'code' },
  Java: { extension: 'java', mime: 'text/plain', app: 'code' },
  Jav: { extension: 'jav', mime: 'text/plain', app: 'code' },
  Jsx: { extension: 'jsx', mime: 'text/plain', app: 'code' },
  Js: { extension: 'js', mime: 'text/plain', app: 'code' },
  Es6: { extension: 'es6', mime: 'text/plain', app: 'code' },
  Mjs: { extension: 'mjs', mime: 'text/plain', app: 'code' },
  Cjs: { extension: 'cjs', mime: 'text/plain', app: 'code' },
  Pac: { extension: 'pac', mime: 'text/plain', app: 'code' },
  Json: { extension: 'json', mime: 'text/plain', app: 'code' },
  Bowerrc: { extension: 'bowerrc', mime: 'text/plain', app: 'code' },
  Jscsrc: { extension: 'jscsrc', mime: 'text/plain', app: 'code' },
  Webmanifest: { extension: 'webmanifest', mime: 'text/plain', app: 'code' },
  JsMap: { extension: 'js.map', mime: 'text/plain', app: 'code' },
  CssMap: { extension: 'css.map', mime: 'text/plain', app: 'code' },
  TsMap: { extension: 'ts.map', mime: 'text/plain', app: 'code' },
  Har: { extension: 'har', mime: 'text/plain', app: 'code' },
  Jslintrc: { extension: 'jslintrc', mime: 'text/plain', app: 'code' },
  Jsonld: { extension: 'jsonld', mime: 'text/plain', app: 'code' },
  Geojson: { extension: 'geojson', mime: 'text/plain', app: 'code' },
  Ipynb: { extension: 'ipynb', mime: 'text/plain', app: 'code' },
  Vuerc: { extension: 'vuerc', mime: 'text/plain', app: 'code' },
  Jsonc: { extension: 'jsonc', mime: 'text/plain', app: 'code' },
  Eslintrc: { extension: 'eslintrc', mime: 'text/plain', app: 'code' },
  EslintrcJson: { extension: 'eslintrc.json', mime: 'text/plain', app: 'code' },
  Jsfmtrc: { extension: 'jsfmtrc', mime: 'text/plain', app: 'code' },
  Jshintrc: { extension: 'jshintrc', mime: 'text/plain', app: 'code' },
  Swcrc: { extension: 'swcrc', mime: 'text/plain', app: 'code' },
  Hintrc: { extension: 'hintrc', mime: 'text/plain', app: 'code' },
  Babelrc: { extension: 'babelrc', mime: 'text/plain', app: 'code' },
  Jsonl: { extension: 'jsonl', mime: 'text/plain', app: 'code' },
  Ndjson: { extension: 'ndjson', mime: 'text/plain', app: 'code' },
  CodeSnippets: { extension: 'code-snippets', mime: 'text/plain', app: 'code' },
  Jl: { extension: 'jl', mime: 'text/plain', app: 'code' },
  Jmd: { extension: 'jmd', mime: 'text/plain', app: 'code' },
  Sty: { extension: 'sty', mime: 'text/plain', app: 'code' },
  Cls: { extension: 'cls', mime: 'text/plain', app: 'code' },
  Bbx: { extension: 'bbx', mime: 'text/plain', app: 'code' },
  Cbx: { extension: 'cbx', mime: 'text/plain', app: 'code' },
  Tex: { extension: 'tex', mime: 'text/plain', app: 'code' },
  Ltx: { extension: 'ltx', mime: 'text/plain', app: 'code' },
  Ctx: { extension: 'ctx', mime: 'text/plain', app: 'code' },
  Bib: { extension: 'bib', mime: 'text/plain', app: 'code' },
  Less: { extension: 'less', mime: 'text/plain', app: 'code' },
  Log: { extension: 'log', mime: 'text/plain', app: 'code' },
  Lua: { extension: 'lua', mime: 'text/plain', app: 'code' },
  Mak: { extension: 'mak', mime: 'text/plain', app: 'code' },
  Mk: { extension: 'mk', mime: 'text/plain', app: 'code' },
  Mkd: { extension: 'mkd', mime: 'text/plain', app: 'code' },
  Mdwn: { extension: 'mdwn', mime: 'text/plain', app: 'code' },
  Mdown: { extension: 'mdown', mime: 'text/plain', app: 'code' },
  Markdown: { extension: 'markdown', mime: 'text/plain', app: 'code' },
  Markdn: { extension: 'markdn', mime: 'text/plain', app: 'code' },
  Mdtxt: { extension: 'mdtxt', mime: 'text/plain', app: 'code' },
  Mdtext: { extension: 'mdtext', mime: 'text/plain', app: 'code' },
  Workbook: { extension: 'workbook', mime: 'text/plain', app: 'code' },
  M: { extension: 'm', mime: 'text/plain', app: 'code' },
  Mm: { extension: 'mm', mime: 'text/plain', app: 'code' },
  Pl: { extension: 'pl', mime: 'text/plain', app: 'code' },
  Pm: { extension: 'pm', mime: 'text/plain', app: 'code' },
  Pod: { extension: 'pod', mime: 'text/plain', app: 'code' },
  T: { extension: 't', mime: 'text/plain', app: 'code' },
  Psgi: { extension: 'psgi', mime: 'text/plain', app: 'code' },
  Raku: { extension: 'raku', mime: 'text/plain', app: 'code' },
  Rakumod: { extension: 'rakumod', mime: 'text/plain', app: 'code' },
  Rakutest: { extension: 'rakutest', mime: 'text/plain', app: 'code' },
  Rakudoc: { extension: 'rakudoc', mime: 'text/plain', app: 'code' },
  Nqp: { extension: 'nqp', mime: 'text/plain', app: 'code' },
  P6: { extension: 'p6', mime: 'text/plain', app: 'code' },
  Pl6: { extension: 'pl6', mime: 'text/plain', app: 'code' },
  Pm6: { extension: 'pm6', mime: 'text/plain', app: 'code' },
  Php: { extension: 'php', mime: 'text/plain', app: 'code' },
  Php4: { extension: 'php4', mime: 'text/plain', app: 'code' },
  Php5: { extension: 'php5', mime: 'text/plain', app: 'code' },
  Phtml: { extension: 'phtml', mime: 'text/plain', app: 'code' },
  Ctp: { extension: 'ctp', mime: 'text/plain', app: 'code' },
  Ps1: { extension: 'ps1', mime: 'text/plain', app: 'code' },
  Psm1: { extension: 'psm1', mime: 'text/plain', app: 'code' },
  Psd1: { extension: 'psd1', mime: 'text/plain', app: 'code' },
  Pssc: { extension: 'pssc', mime: 'text/plain', app: 'code' },
  Psrc: { extension: 'psrc', mime: 'text/plain', app: 'code' },
  Py: { extension: 'py', mime: 'text/plain', app: 'code' },
  Rpy: { extension: 'rpy', mime: 'text/plain', app: 'code' },
  Pyw: { extension: 'pyw', mime: 'text/plain', app: 'code' },
  Cpy: { extension: 'cpy', mime: 'text/plain', app: 'code' },
  Gyp: { extension: 'gyp', mime: 'text/plain', app: 'code' },
  Gypi: { extension: 'gypi', mime: 'text/plain', app: 'code' },
  Pyi: { extension: 'pyi', mime: 'text/plain', app: 'code' },
  Ipy: { extension: 'ipy', mime: 'text/plain', app: 'code' },
  Pyt: { extension: 'pyt', mime: 'text/plain', app: 'code' },
  R: { extension: 'r', mime: 'text/plain', app: 'code' },
  Rhistory: { extension: 'rhistory', mime: 'text/plain', app: 'code' },
  Rprofile: { extension: 'rprofile', mime: 'text/plain', app: 'code' },
  Rt: { extension: 'rt', mime: 'text/plain', app: 'code' },
  Cshtml: { extension: 'cshtml', mime: 'text/plain', app: 'code' },
  Razor: { extension: 'razor', mime: 'text/plain', app: 'code' },
  Rb: { extension: 'rb', mime: 'text/plain', app: 'code' },
  Rbx: { extension: 'rbx', mime: 'text/plain', app: 'code' },
  Rjs: { extension: 'rjs', mime: 'text/plain', app: 'code' },
  Gemspec: { extension: 'gemspec', mime: 'text/plain', app: 'code' },
  Rake: { extension: 'rake', mime: 'text/plain', app: 'code' },
  Ru: { extension: 'ru', mime: 'text/plain', app: 'code' },
  Erb: { extension: 'erb', mime: 'text/plain', app: 'code' },
  Podspec: { extension: 'podspec', mime: 'text/plain', app: 'code' },
  Rbi: { extension: 'rbi', mime: 'text/plain', app: 'code' },
  Rs: { extension: 'rs', mime: 'text/plain', app: 'code' },
  Scss: { extension: 'scss', mime: 'text/plain', app: 'code' },
  Shader: { extension: 'shader', mime: 'text/plain', app: 'code' },
  Sh: { extension: 'sh', mime: 'text/plain', app: 'code' },
  Bash: { extension: 'bash', mime: 'text/plain', app: 'code' },
  Bashrc: { extension: 'bashrc', mime: 'text/plain', app: 'code' },
  BashAliases: { extension: 'bash_aliases', mime: 'text/plain', app: 'code' },
  BashProfile: { extension: 'bash_profile', mime: 'text/plain', app: 'code' },
  BashLogin: { extension: 'bash_login', mime: 'text/plain', app: 'code' },
  Ebuild: { extension: 'ebuild', mime: 'text/plain', app: 'code' },
  Eclass: { extension: 'eclass', mime: 'text/plain', app: 'code' },
  Profile: { extension: 'profile', mime: 'text/plain', app: 'code' },
  BashLogout: { extension: 'bash_logout', mime: 'text/plain', app: 'code' },
  Xprofile: { extension: 'xprofile', mime: 'text/plain', app: 'code' },
  Xsession: { extension: 'xsession', mime: 'text/plain', app: 'code' },
  Xsessionrc: { extension: 'xsessionrc', mime: 'text/plain', app: 'code' },
  Zsh: { extension: 'zsh', mime: 'text/plain', app: 'code' },
  Zshrc: { extension: 'zshrc', mime: 'text/plain', app: 'code' },
  Zprofile: { extension: 'zprofile', mime: 'text/plain', app: 'code' },
  Zlogin: { extension: 'zlogin', mime: 'text/plain', app: 'code' },
  Zlogout: { extension: 'zlogout', mime: 'text/plain', app: 'code' },
  Zshenv: { extension: 'zshenv', mime: 'text/plain', app: 'code' },
  ZshTheme: { extension: 'zsh-theme', mime: 'text/plain', app: 'code' },
  Fish: { extension: 'fish', mime: 'text/plain', app: 'code' },
  Ksh: { extension: 'ksh', mime: 'text/plain', app: 'code' },
  Csh: { extension: 'csh', mime: 'text/plain', app: 'code' },
  Cshrc: { extension: 'cshrc', mime: 'text/plain', app: 'code' },
  Tcshrc: { extension: 'tcshrc', mime: 'text/plain', app: 'code' },
  Yashrc: { extension: 'yashrc', mime: 'text/plain', app: 'code' },
  YashProfile: { extension: 'yash_profile', mime: 'text/plain', app: 'code' },
  Sql: { extension: 'sql', mime: 'text/plain', app: 'code' },
  Dsql: { extension: 'dsql', mime: 'text/plain', app: 'code' },
  Swift: { extension: 'swift', mime: 'text/plain', app: 'code' },
  Ts: { extension: 'ts', mime: 'text/plain', app: 'code' },
  Cts: { extension: 'cts', mime: 'text/plain', app: 'code' },
  Mts: { extension: 'mts', mime: 'text/plain', app: 'code' },
  Tsx: { extension: 'tsx', mime: 'text/plain', app: 'code' },
  Tsbuildinfo: { extension: 'tsbuildinfo', mime: 'text/plain', app: 'code' },
  Xml: { extension: 'xml', mime: 'text/plain', app: 'code' },
  Xsd: { extension: 'xsd', mime: 'text/plain', app: 'code' },
  Ascx: { extension: 'ascx', mime: 'text/plain', app: 'code' },
  Atom: { extension: 'atom', mime: 'text/plain', app: 'code' },
  Axml: { extension: 'axml', mime: 'text/plain', app: 'code' },
  Axaml: { extension: 'axaml', mime: 'text/plain', app: 'code' },
  Bpmn: { extension: 'bpmn', mime: 'text/plain', app: 'code' },
  Cpt: { extension: 'cpt', mime: 'text/plain', app: 'code' },
  Csl: { extension: 'csl', mime: 'text/plain', app: 'code' },
  Csproj: { extension: 'csproj', mime: 'text/plain', app: 'code' },
  CsprojUser: { extension: 'csproj.user', mime: 'text/plain', app: 'code' },
  Dita: { extension: 'dita', mime: 'text/plain', app: 'code' },
  Ditamap: { extension: 'ditamap', mime: 'text/plain', app: 'code' },
  Dtd: { extension: 'dtd', mime: 'text/plain', app: 'code' },
  Ent: { extension: 'ent', mime: 'text/plain', app: 'code' },
  Mod: { extension: 'mod', mime: 'text/plain', app: 'code' },
  Dtml: { extension: 'dtml', mime: 'text/plain', app: 'code' },
  Fsproj: { extension: 'fsproj', mime: 'text/plain', app: 'code' },
  Fxml: { extension: 'fxml', mime: 'text/plain', app: 'code' },
  Iml: { extension: 'iml', mime: 'text/plain', app: 'code' },
  Isml: { extension: 'isml', mime: 'text/plain', app: 'code' },
  Jmx: { extension: 'jmx', mime: 'text/plain', app: 'code' },
  Launch: { extension: 'launch', mime: 'text/plain', app: 'code' },
  Menu: { extension: 'menu', mime: 'text/plain', app: 'code' },
  Mxml: { extension: 'mxml', mime: 'text/plain', app: 'code' },
  Nuspec: { extension: 'nuspec', mime: 'text/plain', app: 'code' },
  Opml: { extension: 'opml', mime: 'text/plain', app: 'code' },
  Owl: { extension: 'owl', mime: 'text/plain', app: 'code' },
  Proj: { extension: 'proj', mime: 'text/plain', app: 'code' },
  Props: { extension: 'props', mime: 'text/plain', app: 'code' },
  Pt: { extension: 'pt', mime: 'text/plain', app: 'code' },
  Publishsettings: {
    extension: 'publishsettings',
    mime: 'text/plain',
    app: 'code',
  },
  Pubxml: { extension: 'pubxml', mime: 'text/plain', app: 'code' },
  PubxmlUser: { extension: 'pubxml.user', mime: 'text/plain', app: 'code' },
  Rbxlx: { extension: 'rbxlx', mime: 'text/plain', app: 'code' },
  Rbxmx: { extension: 'rbxmx', mime: 'text/plain', app: 'code' },
  Rdf: { extension: 'rdf', mime: 'text/plain', app: 'code' },
  Rng: { extension: 'rng', mime: 'text/plain', app: 'code' },
  Rss: { extension: 'rss', mime: 'text/plain', app: 'code' },
  Shproj: { extension: 'shproj', mime: 'text/plain', app: 'code' },
  Storyboard: { extension: 'storyboard', mime: 'text/plain', app: 'code' },
  Targets: { extension: 'targets', mime: 'text/plain', app: 'code' },
  Tld: { extension: 'tld', mime: 'text/plain', app: 'code' },
  Tmx: { extension: 'tmx', mime: 'text/plain', app: 'code' },
  Vbproj: { extension: 'vbproj', mime: 'text/plain', app: 'code' },
  VbprojUser: { extension: 'vbproj.user', mime: 'text/plain', app: 'code' },
  Vcxproj: { extension: 'vcxproj', mime: 'text/plain', app: 'code' },
  VcxprojFilters: {
    extension: 'vcxproj.filters',
    mime: 'text/plain',
    app: 'code',
  },
  Wsdl: { extension: 'wsdl', mime: 'text/plain', app: 'code' },
  Wxi: { extension: 'wxi', mime: 'text/plain', app: 'code' },
  Wxl: { extension: 'wxl', mime: 'text/plain', app: 'code' },
  Wxs: { extension: 'wxs', mime: 'text/plain', app: 'code' },
  Xaml: { extension: 'xaml', mime: 'text/plain', app: 'code' },
  Xbl: { extension: 'xbl', mime: 'text/plain', app: 'code' },
  Xib: { extension: 'xib', mime: 'text/plain', app: 'code' },
  Xlf: { extension: 'xlf', mime: 'text/plain', app: 'code' },
  Xliff: { extension: 'xliff', mime: 'text/plain', app: 'code' },
  Xpdl: { extension: 'xpdl', mime: 'text/plain', app: 'code' },
  Xul: { extension: 'xul', mime: 'text/plain', app: 'code' },
  Xoml: { extension: 'xoml', mime: 'text/plain', app: 'code' },
  Xsl: { extension: 'xsl', mime: 'text/plain', app: 'code' },
  Xslt: { extension: 'xslt', mime: 'text/plain', app: 'code' },
  Yaml: { extension: 'yaml', mime: 'text/plain', app: 'code' },
  Yml: { extension: 'yml', mime: 'text/plain', app: 'code' },
  Eyaml: { extension: 'eyaml', mime: 'text/plain', app: 'code' },
  Eyml: { extension: 'eyml', mime: 'text/plain', app: 'code' },
  Cff: { extension: 'cff', mime: 'text/plain', app: 'code' },
  YamlTmlanguage: {
    extension: 'yaml-tmlanguage',
    mime: 'text/plain',
    app: 'code',
  },
  YamlTmpreferences: {
    extension: 'yaml-tmpreferences',
    mime: 'text/plain',
    app: 'code',
  },
  YamlTmtheme: { extension: 'yaml-tmtheme', mime: 'text/plain', app: 'code' },
  Winget: { extension: 'winget', mime: 'text/plain', app: 'code' },
  Txt: { extension: 'txt', mime: 'text/plain', app: 'code' },
  Csv: { extension: 'csv', mime: 'text/plain', app: 'code' },
  Tsv: { extension: 'tsv', mime: 'text/plain', app: 'code' },
  Jpeg: { extension: 'jpeg', mime: 'image/jpeg', app: 'image' },
  Jpg: { extension: 'jpg', mime: 'image/jpeg', app: 'image' },
  Png: { extension: 'png', mime: 'image/png', app: 'image' },
  Gif: { extension: 'gif', mime: 'image/gif', app: 'image' },
  Svg: { extension: 'svg', mime: 'image/svg+xml', app: 'image' },
  Webp: { extension: 'webp', mime: 'image/webp', app: 'image' },
  Avif: { extension: 'avif', mime: 'image/avif', app: 'image' },
  Bmp: { extension: 'bmp', mime: 'image/bmp', app: 'image' },
  Ico: { extension: 'ico', mime: 'image/x-icon', app: 'image' },
  Tiff: { extension: 'tiff', mime: 'image/tiff', app: 'image' },
  Tif: { extension: 'tif', mime: 'image/tiff', app: 'image' },
  Heic: { extension: 'heic', mime: 'image/heic', app: 'image' },
  Heif: { extension: 'heif', mime: 'image/heif', app: 'image' },
  Tar: { extension: 'tar', mime: 'application/x-tar', app: 'archive' },
  TarGz: { extension: 'tar.gz', mime: 'application/gzip', app: 'archive' },
  Tgz: { extension: 'tgz', mime: 'application/gzip', app: 'archive' },
  Gz: { extension: 'gz', mime: 'application/gzip', app: 'archive' },
  Bz2: { extension: 'bz2', mime: 'application/x-bzip2', app: 'archive' },
  TarBz2: { extension: 'tar.bz2', mime: 'application/x-bzip2', app: 'archive' },
  Tbz2: { extension: 'tbz2', mime: 'application/x-bzip2', app: 'archive' },
  Z: { extension: 'z', mime: 'application/x-compress', app: 'archive' },
  TarZ: { extension: 'tar.z', mime: 'application/x-compress', app: 'archive' },
  Lz: { extension: 'lz', mime: 'application/x-lzip', app: 'archive' },
  TarLz: { extension: 'tar.lz', mime: 'application/x-lzip', app: 'archive' },
  Xz: { extension: 'xz', mime: 'application/x-xz', app: 'archive' },
  TarXz: { extension: 'tar.xz', mime: 'application/x-xz', app: 'archive' },
  Txz: { extension: 'txz', mime: 'application/x-xz', app: 'archive' },
  Lzma: { extension: 'lzma', mime: 'application/x-lzma', app: 'archive' },
  TarLzma: {
    extension: 'tar.lzma',
    mime: 'application/x-lzma',
    app: 'archive',
  },
  Rar: { extension: 'rar', mime: 'application/vnd.rar', app: 'archive' },
  SevenZ: {
    extension: '7z',
    mime: 'application/x-7z-compressed',
    app: 'archive',
  },
  Zst: { extension: 'zst', mime: 'application/zstd', app: 'archive' },
  TarZst: { extension: 'tar.zst', mime: 'application/zstd', app: 'archive' },
  Tzst: { extension: 'tzst', mime: 'application/zstd', app: 'archive' },
  Zip: { extension: 'zip', mime: 'application/zip', app: 'archive' },
  Exe: {
    extension: 'exe',
    mime: 'application/x-msdownload',
    app: 'executable',
  },
  Msi: { extension: 'msi', mime: 'application/x-msi', app: 'executable' },
  Dll: {
    extension: 'dll',
    mime: 'application/x-msdownload',
    app: 'executable',
  },
  Bat: { extension: 'bat', mime: 'application/x-bat', app: 'executable' },
  Cmd: { extension: 'cmd', mime: 'application/x-cmd', app: 'executable' },
  Com: {
    extension: 'com',
    mime: 'application/x-msdownload',
    app: 'executable',
  },
  AppImage: {
    extension: 'appimage',
    mime: 'application/x-executable',
    app: 'executable',
  },
  App: {
    extension: 'app',
    mime: 'application/x-executable',
    app: 'executable',
  },
  Bin: {
    extension: 'bin',
    mime: 'application/octet-stream',
    app: 'executable',
  },
  Deb: {
    extension: 'deb',
    mime: 'application/vnd.debian.binary-package',
    app: 'executable',
  },
  Rpm: { extension: 'rpm', mime: 'application/x-rpm', app: 'executable' },
  Apk: {
    extension: 'apk',
    mime: 'application/vnd.android.package-archive',
    app: 'executable',
  },
  Dmg: {
    extension: 'dmg',
    mime: 'application/x-apple-diskimage',
    app: 'executable',
  },
  Pkg: {
    extension: 'pkg',
    mime: 'application/vnd.apple.installer+xml',
    app: 'executable',
  },
  Crx: {
    extension: 'crx',
    mime: 'application/x-chrome-extension',
    app: 'executable',
  },
  Xpi: { extension: 'xpi', mime: 'application/x-xpinstall', app: 'executable' },
  Mp3: { extension: 'mp3', mime: 'audio/mpeg', app: 'audio' },
  Wav: { extension: 'wav', mime: 'audio/wav', app: 'audio' },
  Ogg: { extension: 'ogg', mime: 'audio/ogg', app: 'audio' },
  Flac: { extension: 'flac', mime: 'audio/flac', app: 'audio' },
  Aac: { extension: 'aac', mime: 'audio/aac', app: 'audio' },
  M4a: { extension: 'm4a', mime: 'audio/mp4', app: 'audio' },
  Wma: { extension: 'wma', mime: 'audio/x-ms-wma', app: 'audio' },
  Mid: { extension: 'mid', mime: 'audio/midi', app: 'audio' },
  Midi: { extension: 'midi', mime: 'audio/midi', app: 'audio' },
  Mp4: { extension: 'mp4', mime: 'video/mp4', app: 'video' },
  Mkv: { extension: 'mkv', mime: 'video/x-matroska', app: 'video' },
  Webm: { extension: 'webm', mime: 'video/webm', app: 'video' },
  Avi: { extension: 'avi', mime: 'video/x-msvideo', app: 'video' },
  Mov: { extension: 'mov', mime: 'video/quicktime', app: 'video' },
  Wmv: { extension: 'wmv', mime: 'video/x-ms-wmv', app: 'video' },
  Mpg: { extension: 'mpg', mime: 'video/mpeg', app: 'video' },
  Mpeg: { extension: 'mpeg', mime: 'video/mpeg', app: 'video' },
  M4v: { extension: 'm4v', mime: 'video/mp4', app: 'video' },
  Flv: { extension: 'flv', mime: 'video/x-flv', app: 'video' },
  F4v: { extension: 'f4v', mime: 'video/mp4', app: 'video' },
  ThreeGp: { extension: '3gp', mime: 'video/3gpp', app: 'video' },
  Ttf: { extension: 'ttf', mime: 'font/ttf', app: 'font' },
  Otf: { extension: 'otf', mime: 'font/otf', app: 'font' },
  Woff: { extension: 'woff', mime: 'font/woff', app: 'font' },
  Woff2: { extension: 'woff2', mime: 'font/woff2', app: 'font' },
  Eot: { extension: 'eot', mime: 'application/vnd.ms-fontobject', app: 'font' },
  Rtf: { extension: 'rtf', mime: 'application/rtf', app: 'document' },
  Odt: {
    extension: 'odt',
    mime: 'application/vnd.oasis.opendocument.text',
    app: 'document',
  },
  Ods: {
    extension: 'ods',
    mime: 'application/vnd.oasis.opendocument.spreadsheet',
    app: 'document',
  },
  Odp: {
    extension: 'odp',
    mime: 'application/vnd.oasis.opendocument.presentation',
    app: 'document',
  },
  Odg: {
    extension: 'odg',
    mime: 'application/vnd.oasis.opendocument.graphics',
    app: 'document',
  },
  Odf: {
    extension: 'odf',
    mime: 'application/vnd.oasis.opendocument.formula',
    app: 'document',
  },
  Epub: { extension: 'epub', mime: 'application/epub+zip', app: 'document' },
  Mobi: {
    extension: 'mobi',
    mime: 'application/x-mobipocket-ebook',
    app: 'document',
  },
  Azw: {
    extension: 'azw',
    mime: 'application/vnd.amazon.ebook',
    app: 'document',
  },
  Azw3: {
    extension: 'azw3',
    mime: 'application/vnd.amazon.ebook',
    app: 'document',
  },
  Djvu: { extension: 'djvu', mime: 'image/vnd.djvu', app: 'document' },
  Xls: { extension: 'xls', mime: 'application/vnd.ms-excel', app: 'document' },
  Ppt: {
    extension: 'ppt',
    mime: 'application/vnd.ms-powerpoint',
    app: 'document',
  },
  Pptx: { extension: 'pptx', mime: 'application/xml', app: 'document' },
  Xlsx: { extension: 'xlsx', mime: 'application/xml', app: 'document' },
  Db: { extension: 'db', mime: 'application/octet-stream', app: 'database' },
  Sqlite: {
    extension: 'sqlite',
    mime: 'application/vnd.sqlite3',
    app: 'database',
  },
  Sqlite3: {
    extension: 'sqlite3',
    mime: 'application/vnd.sqlite3',
    app: 'database',
  },
  Mdb: { extension: 'mdb', mime: 'application/vnd.ms-access', app: 'database' },
  Accdb: {
    extension: 'accdb',
    mime: 'application/vnd.ms-access',
    app: 'database',
  },
  Dbf: { extension: 'dbf', mime: 'application/x-dbf', app: 'database' },
  Plist: { extension: 'plist', mime: 'application/xml', app: 'data' },
  Toml: { extension: 'toml', mime: 'application/toml', app: 'data' },
  Env: { extension: 'env', mime: 'text/plain', app: 'data' },
  Dot: { extension: 'dot', mime: 'text/vnd.graphviz', app: 'data' },
  Gv: { extension: 'gv', mime: 'text/vnd.graphviz', app: 'data' },
  Torrent: {
    extension: 'torrent',
    mime: 'application/x-bittorrent',
    app: 'data',
  },
  Ics: { extension: 'ics', mime: 'text/calendar', app: 'data' },
  Vcf: { extension: 'vcf', mime: 'text/vcard', app: 'data' },
  Ai: { extension: 'ai', mime: 'application/postscript', app: 'vector' },
  Eps: { extension: 'eps', mime: 'application/postscript', app: 'vector' },
  Ps: { extension: 'ps', mime: 'application/postscript', app: 'vector' },
  Dxf: { extension: 'dxf', mime: 'image/vnd.dxf', app: 'vector' },
  Dwg: { extension: 'dwg', mime: 'image/vnd.dwg', app: 'vector' },
  Stl: { extension: 'stl', mime: 'model/stl', app: '3d' },
  Obj: { extension: 'obj', mime: 'model/obj', app: '3d' },
  Fbx: { extension: 'fbx', mime: 'application/octet-stream', app: '3d' },
  Blend: { extension: 'blend', mime: 'application/x-blender', app: '3d' },
  Dae: { extension: 'dae', mime: 'model/vnd.collada+xml', app: '3d' },
  ThreeDs: { extension: '3ds', mime: 'application/x-3ds', app: '3d' },
  Gltf: { extension: 'gltf', mime: 'model/gltf+json', app: '3d' },
  Glb: { extension: 'glb', mime: 'model/gltf-binary', app: '3d' },
  Vhd: { extension: 'vhd', mime: 'application/x-virtualbox-vhd', app: 'vm' },
  Vhdx: { extension: 'vhdx', mime: 'application/x-virtualbox-vhdx', app: 'vm' },
  Vmdk: { extension: 'vmdk', mime: 'application/x-vmdk', app: 'vm' },
  Ova: { extension: 'ova', mime: 'application/x-virtualbox-ova', app: 'vm' },
  Ovf: { extension: 'ovf', mime: 'application/x-virtualbox-ovf', app: 'vm' },
  Iso: { extension: 'iso', mime: 'application/x-iso9660-image', app: 'vm' },
  Img: { extension: 'img', mime: 'application/octet-stream', app: 'vm' },
  Swf: {
    extension: 'swf',
    mime: 'application/x-shockwave-flash',
    app: 'media',
  },
} as const;
