config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  cloud-storage-service:macro_db_secret_key: macro-db-dev
  cloud-storage-service:macro_db_proxy_secret_key: macrodb-rds-proxy-dev
  cloud-storage-service:macro_db_readonly_secret_key: macro-db-readonly-dev
  cloud-storage-service:document_storage_service_auth_key: document-storage-service-auth-key-dev
  cloud-storage-service:jwt_secret_key: fusionauth-jwt-secret-dev
  cloud-storage-service:fusionauth_client_id: fusionauth-client-id-key-dev
  cloud-storage-service:fusionauth_issuer: fusionauth-dev.macro.com
  cloud-storage-service:document_storage_permissions_key: document-storage-permissions-key-dev
  cloud-storage-service:internal_api_key: document-storage-service-auth-key-dev
  cloud-storage-service:sync_service_auth_key: sync-service-key-dev
  cloud-storage-service:authentication_service_secret_key: authentication-service-internal-api-key-dev
  cloud-storage-service:opensearch_password_key: macro-opensearch-password-dev
  cloud-storage-service:macro_cache_secret_key: macro-cache-dev
  cloud-storage-service:github_webhook_secret_key: github-webhook-secret-dev
  cloud-storage-service:github_sync_app_url: https://github.com/apps/dev-macro-app
  cloud-storage-service:github_sync_app_pem: github-sync-app-pem-dev
  cloud-storage-service:github_sync_app_client_id: Iv23lipL80fCypV6UZa1
  cloud-storage-service:livekit_server_url: livekit-server-url-dev
  cloud-storage-service:livekit_api_key: livekit-api-key-dev
  cloud-storage-service:livekit_api_secret: livekit-api-secret-dev
  cloud-storage-service:livekit_transcription_agent_name: macro-transcriber
  cloud-storage-service:call_internal_secret: call-internal-secret-dev
  cloud-storage-service:cal_webhook_secret_key: cal-webhook-secret-dev
  cloud-storage-service:cal_event_type_content_names_key: cal-event-metadata-dev
  cloud-storage-service:meta_pixel_id: "639142540393286"
  cloud-storage-service:meta_access_token: meta-access-token
  cloud-storage-service:anthropic_api_key: anthropic-api-key-dev
  cloud-storage-service:openai_api_key: openai-key
  cloud-storage-service:apple_bundle_id: apple-bundle-id-prod
