config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  cloud-storage-service:macro_db_secret_key: macro-db-prod
  cloud-storage-service:macro_db_proxy_secret_key: macrodb-rds-proxy-prod
  cloud-storage-service:document_storage_service_auth_key: document-storage-service-auth-key-prod
  cloud-storage-service:jwt_secret_key: fusionauth-jwt-secret-prod
  cloud-storage-service:fusionauth_client_id: fusionauth-client-id-key-prod
  cloud-storage-service:fusionauth_issuer: auth.macro.com
  cloud-storage-service:document_storage_permissions_key: document-storage-permissions-key-prod
  cloud-storage-service:internal_api_key: document-storage-service-auth-key-prod
  cloud-storage-service:sync_service_auth_key: sync-service-key-prod
  cloud-storage-service:authentication_service_secret_key: authentication-service-internal-api-key-prod
  cloud-storage-service:opensearch_password_key: macro-opensearch-password-prod
  cloud-storage-service:macro_cache_secret_key: macro-cache-prod
  cloud-storage-service:github_webhook_secret_key: github-webhook-secret-prod
  cloud-storage-service:github_sync_app_url: https://github.com/apps/macro-sync
  cloud-storage-service:github_sync_app_pem: github-sync-app-pem-prod
  cloud-storage-service:github_sync_app_client_id: Iv23ctSZX2wLdqO2iqrS
  cloud-storage-service:apple_team_id: apple-team-id
  cloud-storage-service:apple_bundle_id: apple-bundle-id-prod
  cloud-storage-service:apns_key_id: apns-key-id
  cloud-storage-service:apns_private_key:
    secure: AAABAKWe7JBlRN/BDxH4YFtm06Jry3kcv3jMudROKehPGxqEOEFsukTwQphhJm/+2dk3oFEHvqTDQEF4hOZmdNsa8Lz3f5jP+XgOEgcT2MBkH+QnvOwdYc97B72FRKPi6cmHLPz/9d4S05Jku0XCDhlGgMwYTc7K2vAzdPhCeC+KqAaKzcQmbm9hp5U4CEgo9FY9/GFZbgdHkdeLNC/U2rR8GSNmQoDQoCZEsvj9Btph5XURI6griy4Ou2iypKRRhcw+/jOLxVSOeRoVmKG3FGWsqsmlGC0AmvIKeD3bgrlFnMFUd1/EuP4tDsvhmi7/C7aeRcs+ryXWKFdIzWmnqyfPEu/otczlaMaTU0kiere3b1YsIO4sv8C/1i81FTvy/w==
  cloud-storage-service:fcm_secret_key: fcm-credential-prod
