config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  cloud-storage-service:macro_db_secret_key: macro-db-prod
  cloud-storage-service:macro_db_proxy_secret_key: macrodb-rds-proxy-prod
  cloud-storage-service:macro_db_readonly_secret_key: macro-db-readonly-prod
  cloud-storage-service:document_storage_service_auth_key: document-storage-service-auth-key-prod
  cloud-storage-service:jwt_secret_key: fusionauth-jwt-secret-prod
  cloud-storage-service:fusionauth_client_id: fusionauth-client-id-key-prod
  cloud-storage-service:fusionauth_issuer: auth.macro.com
  cloud-storage-service:document_storage_permissions_key: document-storage-permissions-key-prod
  cloud-storage-service:internal_api_key: document-storage-service-auth-key-prod
  cloud-storage-service:sync_service_auth_key: sync-service-key-prod
  cloud-storage-service:authentication_service_secret_key: authentication-service-internal-api-key-prod
  cloud-storage-service:opensearch_password_key: macro-opensearch-password-prod
  cloud-storage-service:macro_cache_secret_key: macro-cache-prod
  cloud-storage-service:github_webhook_secret_key: github-webhook-secret-prod
  cloud-storage-service:github_sync_app_url: https://github.com/apps/macro-application
  cloud-storage-service:github_sync_app_pem: github-sync-app-pem-prod
  cloud-storage-service:github_sync_app_client_id: Iv23ct0BBwvcPqFORaCI
  cloud-storage-service:livekit_server_url: livekit-server-url-prod
  cloud-storage-service:livekit_api_key: livekit-api-key-prod
  cloud-storage-service:livekit_api_secret: livekit-api-secret-prod
  cloud-storage-service:livekit_transcription_agent_name: macro-transcriber
  cloud-storage-service:call_internal_secret: call-internal-secret-prod
