[package]
edition = "2024"
name = "properties_service"
publish = false
version = "0.1.0"

[lib]
name = "properties_service"
path = "src/lib.rs"

[[bin]]
name = "properties_service_openapi"
path = "src/openapi.rs"

[dependencies]
axum = { workspace = true, features = ["tower-log", "ws"] }
entity_access = { path = "../entity_access" }
macro_authorization = { path = "../macro_authorization" }
models_properties = { path = "../models_properties" }
notification = { path = "../notification" }
properties = { path = "../properties" }
serde_json = { workspace = true }
utoipa = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
