[package]
edition = "2024"
name = "macro_event_broker"
publish = false
version = "0.1.0"

[features]
default = ["outbound"]
outbound = ["dep:kafka_util", "dep:rdkafka"]

[dependencies]
kafka_util = { path = "../kafka_util", optional = true }
rootcause = { workspace = true }
rdkafka = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }
tracing = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
macro_event_topics = { path = "../macro_event_topics" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "time"] }
