[package]
name = "memory_scheduler"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws_lambda_events = { workspace = true, features = ["eventbridge"] }
lambda_runtime = { workspace = true }
macro_aws_config = { path = "../macro_aws_config" }
macro_entrypoint = { path = "../macro_entrypoint" }
memory = { path = "../memory" }
openssl = { workspace = true }
sqlx = { workspace = true }
sqs_client = { path = "../sqs_client", features = ["memory"], default-features = false }
tokio = { workspace = true }
tracing = { workspace = true }
