export ENV := "local"

worker-build: setup worker_build_setup
  worker-build --features create-default-state,bebop-owned-all

# rust both unit and e2e tests
test: worker-build
  npx vitest run
  cargo test

# Run tests without the alarm-keep-alive feature
test-no-alarm: setup worker_build_setup
    worker-build --release --no-default-features --features create-default-state,bebop-owned-all
    npx vitest

setup:
    npm install && cd bebop/ && npx bebopc build

worker_build_setup:
    cargo install worker-build

# initialize the local D1 database used by wrangler dev
migrate-d1-local:
  CI=true npx wrangler d1 migrations apply USER_PEER_MAPPING --local --config wrangler.toml

# run worker using wrangler / miniflare
dev: migrate-d1-local
  npx wrangler dev

# clean testing artifacts
clean:
  rm -rf node_modules .wrangler data

deploy-dev:
  npx wrangler deploy --env dev

migrate-d1-playground:
  CI=true npx wrangler d1 migrations apply USER_PEER_MAPPING --env playground --remote

deploy-playground: migrate-d1-playground
  npx wrangler deploy --env playground

deploy-playground-dry:
  npx wrangler deploy --env playground --dry-run

deploy-dev-dry:
  npx wrangler deploy --env dev --dry-run

deploy-prod:
  npx wrangler deploy --env prod
