[package]
edition = "2024"
name = "soup-filter-projection"
publish = false
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
item-filter-index = { path = "../item_filter_index" }
model_file_type = { path = "../model_file_type" }
models_soup = { path = "../models_soup" }
predicate-index = { path = "../predicate_index" }
thiserror = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
macro_user_id = { path = "../macro_user_id" }
