# Also used as a typed entrypoint for optimistic property-list links.
query EntityProperties($input: SoupInput!) {
  user {
    id
    soup(input: $input) {
      items {
        __typename
        id
        properties {
          ...SoupPropertyFields
        }
      }
    }
  }
}

query GroupEntityProperties($input: GroupedSoupInput!) {
  user {
    id
    groupSoup(input: $input) {
      bins {
        key
        items {
          __typename
          id
          properties {
            ...SoupPropertyFields
          }
        }
      }
    }
  }
}
