# Also used as a typed entrypoint for optimistic property-list links.
query EntityProperties($input: SoupInput!, $documentId: ID! = "", $isDocument: Boolean! = false) {
  user {
    id
    document(documentId: $documentId) @include(if: $isDocument) {
      __typename
      id
      properties {
        ...SoupPropertyFields
      }
    }
    soup(input: $input) @skip(if: $isDocument) {
      items {
        __typename
        id
        properties {
          ...SoupPropertyFields
        }
      }
    }
  }
}

query GroupEntityProperties($input: GroupedSoupInput!) {
  user {
    id
    groupSoup(input: $input) {
      bins {
        key
        items {
          __typename
          id
          properties {
            ...SoupPropertyFields
          }
        }
      }
    }
  }
}
