fragment InitiativeDetailFields on GraphqlSoupInitiative {
  __typename
  id
  displayName
  descriptionDocumentId
  metadata {
    ownerId
    createdAt
    updatedAt
  }
  viewerPermission {
    __typename
    ... on GraphqlAccessLevelPermission {
      accessLevel
    }
  }
  properties {
    ...SoupPropertyFields
  }
  taskCount
  completedTaskCount
  memberIds
  taskIds
  sharePermission {
    __typename
    id
    owner
    linkShare
    linkShareAccessLevel
    teamShareAccessLevel
    channelSharePermissions {
      channelId
      accessLevel
    }
  }
}

query Initiative($initiativeId: ID!) {
  user {
    id
    initiative(initiativeId: $initiativeId) {
      ...InitiativeDetailFields
    }
  }
}

query TaskInitiativeReferences($taskIds: [ID!]!) {
  user {
    id
    taskInitiativeReferences(taskIds: $taskIds) {
      taskId
      state
      initiative {
        __typename
        id
        displayName
      }
    }
  }
}

mutation CreateInitiative($input: CreateInitiativeInput!) {
  createInitiative(input: $input) {
    ...InitiativeDetailFields
  }
}

mutation UpdateInitiative($initiativeId: ID!, $input: UpdateInitiativeInput!) {
  updateInitiative(initiativeId: $initiativeId, input: $input) {
    ...InitiativeDetailFields
  }
}

mutation DeleteInitiative($initiativeId: ID!) {
  deleteInitiative(initiativeId: $initiativeId)
}

mutation AssignInitiativeTasks($initiativeId: ID!, $taskIds: [ID!]!) {
  assignInitiativeTasks(initiativeId: $initiativeId, taskIds: $taskIds) {
    taskId
    status
  }
}

mutation ClearTaskInitiative($taskId: ID!) {
  clearTaskInitiative(taskId: $taskId)
}
