query ItemPreview($input: SoupInput!) {
	user {
		soup(input: $input) {
			items {
				...ItemPreviewFields
			}
		}
	}
}

fragment ItemPreviewFields on GraphqlSoupEntity {
	__typename
	id
	displayName
	... on GraphqlSoupDocument {
		documentName: name
		fileType
		subType {
			__typename
			... on GraphqlTaskSubType {
				isCompleted
			}
		}
	}
	... on GraphqlSoupChat {
		chatName: name
	}
	... on GraphqlSoupProject {
		projectName: name
	}
	... on GraphqlSoupEmailThread {
		emailName: name
		senderEmail
		senderName
	}
	... on GraphqlSoupChannel {
		channelDisplayName: name
		channelType
	}
	... on GraphqlSoupCall {
		customName
		channelName
	}
	... on GraphqlSoupCrmCompany {
		companyName: name
		domains
	}
}
