query Soup($input: SoupInput!) {
	user {
		id
		soup(input: $input) {
			items {
				...SoupItemFields
			}
			nextCursor
		}
	}
}

fragment SoupItemFields on GraphqlSoupEntity {
	__typename
	...SoupEntityCoreFields
	frecencyScore
					... on GraphqlSoupDocument {
						documentName: name
						ownerId
						fileType
						projectId
						createdAt
						updatedAt
						viewedAt
						deletedAt
						subType {
							__typename
							... on GraphqlTaskSubType {
								isCompleted
							}
						}
						properties {
							...SoupPropertyFields
						}
					}
					... on GraphqlSoupChat {
						chatName: name
						ownerId
						projectId
						isPersistent
						createdAt
						updatedAt
						viewedAt
						deletedAt
						properties {
							...SoupPropertyFields
						}
					}
					... on GraphqlSoupProject {
						projectName: name
						ownerId
						parentId
						createdAt
						updatedAt
						viewedAt
						deletedAt
						properties {
							...SoupPropertyFields
						}
					}
					... on GraphqlSoupEmailThread {
						providerId
						ownerId
						inboxVisible
						linkId
						latestInboundMessageTs
						emailName: name
						snippet
						senderEmail
						senderName
						senderPhotoUrl
						isRead
						isDraft
						isImportant
						projectId
						sortTs
						createdAt
						updatedAt
						viewedAt
						participants {
							id
							linkId
							name
							email
							sfsPhotoUrl
						}
						attachments {
							id
							messageId
							providerAttachmentId
							filename
							mimeType
							sizeBytes
							contentId
							createdAt
						}
						labels {
							id
							linkId
							providerLabelId
							name
							createdAt
							messageListVisibility
							labelListVisibility
							type
						}
						properties {
							...SoupPropertyFields
						}
						latestContentMessage {
							__typename
							id
							threadId
							linkId
							subject
							snippet
							internalDateTs
							sentAt
							isRead
							isStarred
							isSent
							hasAttachments
							from {
								email
								name
								photoUrl
							}
							to {
								email
								name
								photoUrl
							}
							cc {
								email
								name
								photoUrl
							}
							bcc {
								email
								name
								photoUrl
							}
							labels {
								providerLabelId
								name
							}
							bodyParsed
							bodyText
							bodyHtmlSanitized
							bodyMacro
							bodyReplyless
							createdAt
							updatedAt
						}
					}
					... on GraphqlSoupChannel {
						channelName: name
						channelType
						ownerId
						organizationId
						channelTeamId: teamId
						createdAt
						updatedAt
						viewedAt
						interactedAt
						isParticipant
						participants {
							channelId
							userId
							role
							joinedAt
							leftAt
						}
						latestMessage {
							...SoupChannelMessageFields
						}
						latestNonThreadMessage {
							...SoupChannelMessageFields
						}
					}
					... on GraphqlSoupChannelMessage {
						channelId
						senderId
						content
						createdAt
						updatedAt
						effectiveUpdatedAt
						replyCount
					}
					... on GraphqlSoupCall {
						channelId
						channelName
						createdBy
						customName
						summary
						startedAt
						endedAt
						durationMs
						isActive
						status
						attended
						participants {
							userId
							joinedAt
							leftAt
						}
						properties {
							...SoupPropertyFields
						}
					}
					... on GraphqlSoupCrmCompany {
						crmTeamId: teamId
						crmCompanyName: name
						description
						emailSync
						hidden
						createdAt
						updatedAt
						viewedAt
						domains
						properties {
							...SoupPropertyFields
						}
					}
					... on GraphqlSoupForeignEntity {
						foreignEntityId
						foreignEntitySource
						storedForId
						storedForAuthEntity
						sourceMetadata
						createdAt
						updatedAt
					}
}

fragment SoupEntityCoreFields on GraphqlSoupEntity {
	id
	entityType
	displayName
	isFavorited
	notifications {
		...SoupNotificationFields
	}
}

fragment SoupPropertyFields on GraphqlProperty {
	id
	propertyDefinitionId
	displayName
	dataType
	isMultiSelect
	specificEntityType
	isSystem
	isMetadata
	value {
		__typename
		... on GraphqlBooleanPropertyValue {
			boolValue: value
		}
		... on GraphqlNumberPropertyValue {
			numberValue: value
		}
		... on GraphqlStringPropertyValue {
			stringValue: value
		}
		... on GraphqlDatePropertyValue {
			dateValue: value
		}
		... on GraphqlSelectOptionPropertyValue {
			optionIds
		}
		... on GraphqlEntityReferencePropertyValue {
			references {
				entityId
				entityType
				specificMessageId
			}
		}
		... on GraphqlLinkPropertyValue {
			urls
		}
	}
}

fragment SoupChannelMessageFields on GraphqlSoupChannelMessagePreview {
	messageId
	channelId
	threadId
	senderId
	content
	createdAt
	updatedAt
	deletedAt
	mentions
}

fragment SoupNotificationFields on GraphqlSoupNotification {
	id
	eventType
	entityType
	entityId
	sent
	done
	seen
	createdAt
	viewedAt
	updatedAt
	senderId
	metadata
}
