name: "Deploy lexical service dev"
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  # We do not want to cancel a deployment if it's in progress. That could lead to a broken deployment.
  cancel-in-progress: false

jobs:
  deploy_lexical_service:
    uses: ./.github/workflows/deploy-lexical-service.yml
    with:
      environment: dev
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
