name: Migrate Macro Database

on:
  workflow_dispatch:

jobs:
  migrate-db:
    name: Run Database Migrations (dev)
    runs-on: db-migrator-runner
    steps:
      - name: Run migrations for dev
        uses: ./.github/actions/migrate-cloud-storage-db
        with:
          environment: dev
